INSERT INTO AFFERENTE (CODICE_FISCALE, NOME, COGNOME, DATA_NASCITA, LUOGO_NASCITA, TEMPO, RUOLO, TITOLO_STUDIO, UNIVERSITA, NOME_DIPARTIMENTO, PUNTEGGIO, RELATORE, FASCIA, STATO) VALUES
 ('FRCNBL87M155F5AL', 'Annabell', 'Fraczek', '1987-08-15', 'DALLAS', 'pieno', 'professore', 'dottorato di ricerca', 'Birla Institute of Technology and Science', 'Informatica', null, 'Annabell Fraczek', 'prima', null),
 ('SHRSRN84M24D4Z6M', 'Sarine', 'Shrimptone', '1984-08-24', 'MOREHEAD', 'parziale', 'professore', 'laurea', 'University of Technology and Life Sciences', 'Matematica',81, null, 'prima', null),
 ('GCVRGG84R165BU1K', 'Reggie', 'Giacovetti', '1984-10-16', 'HUGO', 'pieno', 'professore', 'dottorato di ricerca', 'Sanford-Brown Institute', 'Fisica', null, 'Reggie Giacovetti', 'seconda', null),
 ('SPDNGI91T553JO6K', 'Inga', 'Spadollini', '1991-12-15', 'RED CLOUD', 'parziale', 'professore', 'dottorato di ricerca', 'City University Programs in Bulgaria ', 'Medicina', null, 'Inga Spadollini', 'seconda', null),
 ('BLSPHL86T54MY53B', 'Phelia', 'Blasiak', '1986-12-14', 'HAYTI', 'pieno', 'ricercatore', 'laurea', 'Universidad Nacional de Lomas de Zamora', 'Ingegneria',93, null, null, 'confermato'),
 ('DYSKRD90M0514LWW', 'Konrad', 'Dysart', '1990-08-05', 'CHARLOTTE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Pontifcia Università Gregoriana', 'Architettura', null, 'Konrad Dysart', null, 'confermato'),
 ('LTHLNA79T5769PCJ', 'Ailina', 'Louth', '1979-12-17', 'PARK RIDGE', 'pieno', 'ricercatore', 'laurea', 'University of Sussex', 'Economia',94, null, null, 'confermato'),
 ('CRDCNY88S08FL42T', 'Corney', 'Creedland', '1988-11-08', 'GREENFIELD', 'parziale', 'ricercatore', 'laurea', 'Saudi Electronic University', 'Psicologia',66, null, null, 'non confermato'),
 ('GLLJRB67T085MLNJ', 'Jareb', 'Gillise', '1967-12-08', 'HOMESTEAD', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Islamic Azad University, Qom', 'Filosofia', null, 'Jareb Gillise', null, 'confermato'),
 ('CSTCPO94P02FBHTI', 'Coop', 'Castaignet', '1994-09-02', 'BELL', 'pieno', 'ricercatore', 'laurea', 'Auchi Polytechnic', 'Scienze Politiche',78, null, null, 'confermato'),
 ('BRFSMS73D12Y5DOH', 'Seamus', 'Burfoot', '1973-04-12', 'LOS ANGELES', 'parziale', 'professore', 'dottorato di ricerca', 'Mogilev State University A.A. Kuleshov', 'Informatica', null, 'Seamus Burfoot', 'seconda', null),
 ('VNDHCL84M06V4WTL', 'Herculie', 'Van Dalen', '1984-08-06', 'CHATTANOOGA', 'parziale', 'professore', 'dottorato di ricerca', 'Technical University of Civil Engineering Bucharest', 'Matematica', null, 'Herculie Van Dalen', 'seconda', null),
 ('BRCDCA92H65JQJHI', 'Dacia', 'Burchfield', '1992-06-25', 'LAGUNA HILLS', 'pieno', 'professore', 'dottorato di ricerca', 'Evangel University', 'Fisica', null, 'Dacia Burchfield', 'prima', null),
 ('SHRNMR64C29JEGNT', 'Annemarie', 'Sherwen', '1964-03-29', 'GARDNER', 'pieno', 'professore', 'laurea', 'Beijing Forestry University', 'Medicina',101, null, 'prima', null),
 ('CGGMTY90B28W4T2J', 'Martynne', 'Coggill', '1990-02-28', 'LONG BEACH', 'parziale', 'professore', 'dottorato di ricerca', 'Bicol University', 'Ingegneria', null, 'Martynne Coggill', 'seconda', null),
 ('FRDJDN74R591NE6V', 'Jordana', 'Frood', '1974-10-19', 'COLUMBUS', 'pieno', 'ricercatore', 'laurea', 'Georgetown College', 'Architettura',79, null, null, 'non confermato'),
 ('STCLSH62D656IINI', 'Leisha', 'Stockle', '1962-04-25', 'FLOWER MOUND', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Korea Maritime University', 'Economia', null, 'Leisha Stockle', null, 'confermato'),
 ('GSSJRD65T16IR7RU', 'Jarrod', 'Gussie', '1965-12-16', 'MORRISTOWN', 'parziale', 'ricercatore', 'laurea', 'Brooks Institute of Photography', 'Psicologia',86, null, null, 'non confermato'),
 ('JSVMRS62L24GWE4K', 'Maris', 'Josovitz', '1962-07-24', 'LAS CRUCES', 'parziale', 'professore', 'laurea', 'Institute of Finance', 'Filosofia',110, null, 'seconda', null),
 ('MNDLYN90T01ZDF7A', 'Elwyn', 'Mound', '1990-12-01', 'HAMILTON', 'pieno', 'professore', 'laurea', 'American Academy of Nutrition', 'Scienze Politiche',67, null, 'seconda', null),
 ('SMTRNL62H30D6RFU', 'Reynolds', 'Smithen', '1962-06-30', 'ELMIRA', 'pieno', 'professore', 'dottorato di ricerca', 'Western Washington University', 'Informatica', null, 'Reynolds Smithen', 'seconda', null),
 ('PCKLEE61P12NF7OX', 'Lee', 'Pickerill', '1961-09-12', 'FAIRBORN', 'pieno', 'ricercatore', 'dottorato di ricerca', 'St.James''s School of Medicine, Bonaire', 'Matematica', null, 'Lee Pickerill', null, 'confermato'),
 ('SMNCSN90S11AW8YJ', 'Cassandry', 'Simonini', '1990-11-11', 'SHAKER HTS', 'parziale', 'ricercatore', 'laurea', 'Institute of Business Administration Sukkur', 'Fisica',69, null, null, 'non confermato'),
 ('GLBRNN93R078MQKZ', 'Rosanne', 'Golby', '1993-10-07', 'ONTARIO', 'parziale', 'professore', 'laurea', 'Karachi Institute Of Economics And Technology', 'Medicina',70, null, 'seconda', null),
 ('JCCSSM73C253LABM', 'Sigismundo', 'Jeacock', '1973-03-25', 'EASLEY', 'parziale', 'professore', 'laurea', 'Texas A&M University', 'Ingegneria',67, null, 'seconda', null),
 ('BRNWNN84A18IQUMR', 'Wynne', 'Bront', '1984-01-18', 'ZACHARY', 'parziale', 'professore', 'dottorato di ricerca', 'William Woods University', 'Architettura', null, 'Wynne Bront', 'seconda', null),
 ('KDDTSN60P65SEZ6C', 'Tomasina', 'Kidde', '1960-09-25', 'ALBERTSON', 'parziale', 'ricercatore', 'laurea', 'Nanchang University', 'Economia',106, null, null, 'non confermato'),
 ('JYSRDA77A5897EEN', 'Arda', 'Joyes', '1977-01-18', 'PHOENIX', 'pieno', 'professore', 'dottorato di ricerca', 'Universitas Nasional Jakarta', 'Psicologia', null, 'Arda Joyes', 'seconda', null),
 ('TTLKRB89R301HIYT', 'Kirbie', 'Titlow', '1989-10-30', 'ABILENE', 'pieno', 'ricercatore', 'laurea', 'Maharishi Dayanand University, Rohtak (Haryana)', 'Filosofia', 68, null, null, 'confermato'),
 ('SMRVVI89P17EVQ8X', 'Vivie', 'Smorthwaite', '1989-09-17', 'NEWPORT NEWS', 'parziale', 'professore', 'laurea', 'East Stroudsburg State University', 'Scienze Politiche',96, null, 'prima', null),
 ('BLMMRO78D63M1H1V', 'Moria', 'Blemen', '1978-04-23', 'LAKELAND', 'parziale', 'professore', 'dottorato di ricerca', 'Tashkent School of Finance', 'Informatica', null, 'Moria Blemen', 'seconda', null),
 ('FTHSPH76C20E2HIR', 'Stephannie', 'Faithfull', '1976-03-20', 'CLARKSVILLE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Universidad Tecnológica América', 'Matematica', null, 'Stephannie Faithfull', null, 'confermato'),
 ('BNKNBL84D016HC9B', 'Anabel', 'Benkin', '1984-04-01', 'BOSTON', 'pieno', 'professore', 'dottorato di ricerca', 'Gunma University', 'Fisica', null, 'Anabel Benkin', 'prima', null),
 ('MYHWTH94S113SEDH', 'Worthy', 'Mayhead', '1994-11-11', 'RANGELY', 'pieno', 'professore', 'laurea', 'Universitas Negeri Surabaya', 'Medicina',66, null, 'prima', null),
 ('LKNRLY76S17YOHPD', 'Arley', 'Lakenton', '1976-11-17', 'CHICAGO', 'pieno', 'professore', 'laurea', 'Zayed University', 'Ingegneria',72, null, 'seconda', null),
 ('KRTCHL87D16OE63W', 'Cathlene', 'Kirtlan', '1987-04-16', 'CHARLOTTE', 'parziale', 'professore', 'dottorato di ricerca', 'American University in Bulgaria', 'Architettura', null, 'Cathlene Kirtlan', 'prima', null),
 ('SLNCTN87T04RMLJU', 'Courtney', 'Oseland', '1987-12-04', 'MIDLAND', 'pieno', 'ricercatore', 'laurea', 'Open University of Hong Kong', 'Economia',82, null, null, 'non confermato'),
 ('CRCJNL83E18JQRSQ', 'Jannelle', 'Croucher', '1983-05-18', 'RANDALLSTOWN', 'pieno', 'ricercatore', 'laurea', 'Madison University (Distance Education)', 'Psicologia', 75, null, null, 'confermato'),
 ('SMYRVE67P55JYEFL', 'Reeva', 'Smyth', '1967-09-15', 'ORANGEBURG', 'pieno', 'professore', 'dottorato di ricerca', 'CETYS Universidad', 'Filosofia', null, 'Reeva Smyth', 'seconda', null),
 ('DVRBRL86T03MPQ0U', 'Byrle', 'Deveril', '1986-12-03', 'MIDDLETOWN', 'parziale', 'professore', 'laurea', 'Kanagawa University', 'Scienze Politiche',80, null, 'seconda', null),
 ('SKNCRN88P58GOTCR', 'Clarinda', 'Skinn', '1988-09-18', 'EL CAMPO', 'pieno', 'ricercatore', 'laurea', 'Ranchi University', 'Informatica',92, null, null, 'confermato'),
 ('CVCCSS61H19RRMUH', 'Cass', 'Iacovucci', '1961-06-19', 'WHITESTONE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Czech Technical University of Prague', 'Matematica', null, 'Cass Iacovucci', null, 'confermato'),
 ('HSNKPI94S10BGUJH', 'Kip', 'Hasney', '1994-11-10', 'JONESBORO', 'parziale', 'ricercatore', 'laurea', 'York College of Pennsylvania', 'Fisica',84, null, null, 'non confermato'),
 ('BRDBRT62H27PXMWH', 'Berte', 'Brodhead', '1962-06-27', 'FORT WORTH', 'pieno', 'professore', 'dottorato di ricerca', 'École nationale d''administration publique, Université du Québec', 'Medicina', null, 'Berte Brodhead', 'prima', null),
 ('MRPRLL90B20RIJ4D', 'Rozelle', 'Morphet', '1990-02-20', 'GALION', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Makerere University', 'Ingegneria', null, 'Rozelle Morphet', null, 'confermato'),
 ('CVLKRR92M239ZKVR', 'Korrie', 'Covelle', '1992-08-23', 'LONDON', 'pieno', 'professore', 'dottorato di ricerca', 'Western University', 'Architettura', null, 'Korrie Covelle', 'seconda', null),
 ('KBLLGR70M44A71AR', 'Allegra', 'Kobelt', '1970-08-04', 'TUPELO', 'pieno', 'professore', 'dottorato di ricerca', 'Ecole Nationale Supérieur de Géologie de Nancy', 'Economia', null, 'Allegra Kobelt', 'seconda', null),
 ('LBBBDC81S05NS7MH', 'Bendick', 'Labba', '1981-11-05', 'LOUISVILLE', 'parziale', 'professore', 'dottorato di ricerca', 'University of Wisconsin - La Crosse', 'Psicologia', null, 'Bendick Labba', 'prima', null),
 ('LLWRRK87H212SL6T', 'Rurik', 'Allwright', '1987-06-21', 'MECHANICSBURG', 'parziale', 'professore', 'laurea', 'Universidad de Hermosillo', 'Filosofia',89, null, 'seconda', null),
 ('HNDCLD82D25UQKJK', 'Claude', 'Hand', '1982-04-25', 'DES MOINES', 'pieno', 'professore', 'laurea', 'University of Texas at El Paso', 'Scienze Politiche',75, null, 'prima', null),
 ('RSTWST77L148UTSS', 'Winston', 'Rosita', '1977-07-14', 'CHARLOTTE', 'parziale', 'professore', 'laurea', 'Universidade de Tocantins', 'Informatica',105, null, 'seconda', null),
 ('HMOKPR88S30NIC8O', 'Kaspar', 'Ohm', '1988-11-30', 'SACRAMENTO', 'pieno', 'professore', 'dottorato di ricerca', 'Burapha University', 'Matematica', null, 'Kaspar Ohm', 'seconda', null),
 ('TRGTNO84E27W8GGF', 'Tonie', 'Tregunnah', '1984-05-27', 'OAK PARK', 'parziale', 'professore', 'dottorato di ricerca', 'City University of New York (CUNY)', 'Fisica', null, 'Tonie Tregunnah', 'seconda', null),
 ('BMNJMY94E06PL3GD', 'Jimmy', 'Beminster', '1994-05-06', 'WEST PALM BEACH', 'parziale', 'ricercatore', 'dottorato di ricerca', 'South East European University', 'Medicina', null, 'Jimmy Beminster', null, 'non confermato'),
 ('SNSLNE64L245TAOF', 'Elene', 'Sansun', '1964-07-24', 'BRENTWOOD', 'parziale', 'professore', 'laurea', 'United States Military Academy', 'Ingegneria',71, null, 'prima', null),
 ('NSCBRD69A03QHA5L', 'Brodie', 'Anscott', '1969-01-03', 'NEWTON', 'pieno', 'professore', 'dottorato di ricerca', '1 December University of Alba Iulia', 'Architettura', null, 'Brodie Anscott', 'seconda', null),
 ('MLLSSY90R06ZBMTY', 'Sissy', 'Melly', '1990-10-06', 'CHICAGO', 'parziale', 'professore', 'laurea', 'Faculdade Integradas do Ceará', 'Economia',98, null, 'prima', null),
 ('TRSDRC90E09WJRAH', 'Darice', 'Trussell', '1990-05-09', 'SHAKER HTS', 'parziale', 'ricercatore', 'dottorato di ricerca', 'University of Bari', 'Psicologia', null, 'Darice Trussell', null, 'non confermato'),
 ('SHFRGN70B151UHZY', 'Regan', 'Aishford', '1970-02-15', 'COLUMBUS', 'parziale', 'professore', 'laurea', 'Universidad Autónoma de Centro América', 'Filosofia',107, null, 'seconda', null),
 ('WTHRSM72H25I9XYU', 'Ransom', 'Witherspoon', '1972-06-25', 'HOLLY SPRINGS', 'parziale', 'professore', 'laurea', 'University of Zadar', 'Scienze Politiche',70, null, 'seconda', null),
 ('BLLBNN65A304NQ0R', 'Bonni', 'Billitteri', '1965-01-30', 'CINCINNATI', 'pieno', 'professore', 'laurea', 'Midwestern State University', 'Informatica',70, null, 'prima', null),
 ('HLVLVN63S549S51P', 'Lavina', 'Halvorsen', '1963-11-14', 'KANSAS CITY', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Lithunian Academy of Music and Theatre', 'Matematica', null, 'Lavina Halvorsen', null, 'confermato'),
 ('HTSJFR82B18I1OIX', 'Jeffry', 'Huitson', '1982-02-18', 'CHICAGO', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Universidad de La Habana', 'Fisica', null, 'Jeffry Huitson', null, 'confermato'),
 ('NYSHRS74A10X965F', 'Harrison', 'Nayshe', '1974-01-10', 'MIAMI', 'parziale', 'professore', 'laurea', 'Universiti Teknologi Malaysia', 'Medicina',97, null, 'prima', null),
 ('MPLCRC74T11PLD1K', 'Cedric', 'Mapledorum', '1974-12-11', 'DU QUOIN', 'parziale', 'professore', 'dottorato di ricerca', 'Universidad Pontificia Bolivariana', 'Ingegneria', null, 'Cedric Mapledorum', 'seconda', null),
 ('BBTHLN82B257UE9L', 'Helaine', 'Abbitt', '1982-02-25', 'CHARLOTTE', 'pieno', 'professore', 'dottorato di ricerca', 'Punjab University College of Information Tecnology', 'Architettura', null, 'Helaine Abbitt', 'prima', null),
 ('FRRGVR75T035YEEE', 'Guenevere', 'Farrington', '1975-12-03', 'KAILUA', 'pieno', 'professore', 'laurea', 'Asia E University', 'Economia',73, null, 'seconda', null),
 ('PNDKRY66P24OFAED', 'Kerry', 'Pendleton', '1966-09-24', 'MIAMI', 'parziale', 'professore', 'laurea', 'Tyumen State Agricultural Academy', 'Psicologia',95, null, 'seconda', null),
 ('KTTKYL66E12FK92S', 'Karyl', 'Kitt', '1966-05-12', 'NEW MARTINSVILLE', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad de la Fraternidad de Agrupaciones Santo Tomas de Aquino (FASTA)', 'Filosofia', null, 'Karyl Kitt', 'prima', null),
 ('JNDVEE81P14EPHML', 'Eve', 'Jendas', '1981-09-14', 'TUCSON', 'parziale', 'professore', 'laurea', 'Universidad de Córdoba', 'Scienze Politiche',97, null, 'prima', null),
 ('NSLTNR82D16JVY7Q', 'Tanner', 'Anselmi', '1982-04-16', 'SACRAMENTO', 'parziale', 'ricercatore', 'laurea', 'University of Minnesota - Crookston', 'Informatica',108, null, null, 'confermato'),
 ('TRUTBL90L07X9Q2Q', 'Tybalt', 'True', '1990-07-07', 'INDIANAPOLIS', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Universidad Internacional de Andalucía, Sede Antonio Machado de Baeza', 'Matematica', null, 'Tybalt True', null, 'confermato'),
 ('SLNSHN87B135NRNZ', 'Shaun', 'Solon', '1987-02-13', 'ATLANTA', 'parziale', 'professore', 'dottorato di ricerca', 'Estonian Academy of Music and Theatre', 'Fisica', null, 'Shaun Solon', 'prima', null),
 ('SLSRNL71R052SZMH', 'Reynold', 'Slisby', '1971-10-05', 'DALLAS', 'parziale', 'professore', 'laurea', 'Mount Vernon Nazarene College', 'Medicina',83, null, 'prima', null),
 ('TRDDTH84M04NJVHU', 'Dorothy', 'Truder', '1984-08-04', 'SAN ANTONIO', 'parziale', 'professore', 'laurea', 'East China Normal University', 'Ingegneria',106, null, 'prima', null),
 ('GWNBNR79D27MAKWS', 'Barnard', 'Gwinnel', '1979-04-27', 'LA PLACE', 'pieno', 'professore', 'laurea', 'University of Pittsburgh', 'Architettura',88, null, 'prima', null),
 ('BDXCCK84L14XX65J', 'Chicky', 'Baudoux', '1984-07-14', 'GLENDALE', 'pieno', 'professore', 'dottorato di ricerca', 'Hong Bang University International', 'Economia', null, 'Chicky Baudoux', 'prima', null),
 ('GMMGBY64B24K6GWR', 'Gabby', 'Gommes', '1964-02-24', 'TEMPLE', 'parziale', 'ricercatore', 'laurea', 'University of Nova Gorica', 'Psicologia',110, null, null, 'confermato'),
 ('BCNLDR79T705Z3TL', 'Leodora', 'Bacon', '1979-12-30', 'CHARLOTTE', 'pieno', 'ricercatore', 'laurea', 'Cambodia University of Specialties', 'Filosofia',81, null, null, 'confermato'),
 ('SHRKWN83D20VCESF', 'Kerwinn', 'Shorto', '1983-04-20', 'NORRIDGE', 'parziale', 'professore', 'laurea', 'Aletheia University', 'Scienze Politiche',102, null, 'seconda', null),
 ('HNNYLU72T08AFOUM', 'Yule', 'Hunn', '1972-12-08', 'BALTIMORE', 'parziale', 'ricercatore', 'laurea', 'Saito College', 'Informatica',86, null, null, 'confermato'),
 ('CLLBNY64R08OBRYO', 'Bonny', 'Collister', '1964-10-08', 'WINCHESTER', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Sugino Women''s College', 'Matematica', null, 'Bonny Collister', null, 'non confermato'),
 ('PSSLRD85A16LJDTI', 'Alfred', 'Passey', '1985-01-16', 'COLORADO SPRINGS', 'parziale', 'professore', 'laurea', 'Texas College', 'Fisica',91, null, 'seconda', null),
 ('GDDDSL73A59I3UAN', 'Drusilla', 'Gooddy', '1973-01-19', 'BREWSTER', 'pieno', 'professore', 'laurea', 'Universitas Pasundan', 'Medicina',78, null, 'prima', null),
 ('PBLLXA73R26YI45P', 'Alex', 'Peebles', '1973-10-26', 'DENVER', 'parziale', 'professore', 'laurea', 'Universitat de Lleida', 'Ingegneria',69, null, 'prima', null),
 ('RDDBMB88M24WAETR', 'Bambi', 'Riddler', '1988-08-24', 'ORANGEBURG', 'parziale', 'professore', 'laurea', 'Pennsylvania State University - Schuylkill', 'Architettura',107, null, 'seconda', null),
 ('PTRKTN91A2262P2S', 'Katine', 'Paternoster', '1991-01-22', 'MERCED', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Russel Sage College', 'Economia', null, 'Katine Paternoster', null, 'confermato'),
 ('DNSCBB79L102UMPV', 'Cobb', 'Dinsmore', '1979-07-10', 'ADA', 'parziale', 'professore', 'dottorato di ricerca', 'Arizona State University, Tempe Campus', 'Psicologia', null, 'Cobb Dinsmore', 'seconda', null),
 ('KRKCRI85T22QNYVP', 'Ciro', 'Kirkup', '1985-12-22', 'HIALEAH', 'pieno', 'professore', 'dottorato di ricerca', 'University of Management and Technology', 'Filosofia', null, 'Ciro Kirkup', 'prima', null),
 ('MCSFDL62L59OOIAK', 'Fredelia', 'Mcsarry', '1962-07-19', 'LAS VEGAS', 'pieno', 'professore', 'dottorato di ricerca', 'Libya Open University', 'Scienze Politiche', null, 'Fredelia Mcsarry', 'seconda', null),
 ('DMBMLL91E01IMG3X', 'Moselle', 'Dumbar', '1991-05-01', 'BURKESVILLE', 'pieno', 'professore', 'laurea', 'Universidad San Marcos', 'Informatica',94, null, 'seconda', null),
 ('JSTJND63R16W9UBF', 'Jsandye', 'Jesty', '1963-10-16', 'COLEBROOK', 'pieno', 'professore', 'dottorato di ricerca', 'Aomori Public College', 'Matematica', null, 'Jsandye Jesty', 'seconda', null),
 ('BRNFNN67B263A3PX', 'Fernando', 'Bernolet', '1967-02-26', 'MEADVILLE', 'pieno', 'professore', 'laurea', 'Khmelnitsky National University', 'Fisica',85, null, 'seconda', null),
 ('KNVCRO80R17X2YGE', 'Corie', 'Knivett', '1980-10-17', 'STATEN ISLAND', 'parziale', 'professore', 'dottorato di ricerca', 'New York Institute of Technology', 'Medicina', null, 'Corie Knivett', 'prima', null),
 ('LNGRKY60H118O44P', 'Ricky', 'Longland', '1960-06-11', 'BOSTON', 'pieno', 'ricercatore', 'laurea', 'Universidad Nacional de San Antonio Abad', 'Ingegneria',103, null, null, 'non confermato'),
 ('WCKBRD90L06OJHEQ', 'Baird', 'Wickens', '1990-07-06', 'PIGGOTT', 'pieno', 'professore', 'laurea', 'Shanghai University of Engineering Science', 'Architettura',76, null, 'prima', null),
 ('TWNRVA75D22S5GEU', 'Arv', 'Townson', '1975-04-22', 'SISTERSVILLE', 'pieno', 'ricercatore', 'laurea', 'Hiram College', 'Economia',87, null, null, 'confermato'),
 ('CCCSWA60M12YWCAV', 'Saw', 'Cacacie', '1960-08-12', 'MEMPHIS', 'parziale', 'professore', 'dottorato di ricerca', 'Gomel State Medical University', 'Psicologia', null, 'Saw Cacacie', 'seconda', null),
 ('HDCCHL73M13B33UU', 'Chlo', 'Headech', '1973-08-13', 'CHARLOTTE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Our Lady of the Lake University', 'Filosofia', null, 'Chlo Headech', null, 'non confermato'),
 ('RNGWTL93S23HM4PU', 'Westley', 'Earingey', '1993-11-23', 'KAILUA', 'parziale', 'ricercatore', 'dottorato di ricerca', 'First Global University to teaching Jainism', 'Scienze Politiche', null, 'Westley Earingey', null, 'non confermato'),
 ('WRGJRD87L18JCI4V', 'Jarred', 'Wraighte', '1987-07-18', 'SOMERVILLE', 'pieno', 'ricercatore', 'laurea', 'Texas A&M University - Kingsville', 'Informatica',91, null, null, 'non confermato'),
 ('HSLRBE90E09D9PPT', 'Rebe', 'Hasel', '1990-05-09', 'PORT JEFFERSON', 'parziale', 'professore', 'laurea', 'Fachhochschule Konstanz, Hochschule für Technik, Wirtschaft und Gestaltung', 'Matematica', 66, null, 'seconda', null),
 ('LNYWMR75T121DOWQ', 'Wilmer', 'Linay', '1975-12-12', 'JACKSON', 'pieno', 'professore', 'laurea', 'Sierra Nevada College', 'Fisica',83, null, 'seconda', null),
 ('PRKVLL63A20HCA1J', 'Averell', 'Perkinson', '1963-01-20', 'LINCOLN', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Institute of Business Administration Sukkur', 'Medicina', null, 'Averell Perkinson', null, 'non confermato'),
 ('LRDBNN84A08C69KL', 'Blinny', 'Lauridsen', '1984-01-08', 'HAWKINSVILLE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Sapporo International University', 'Ingegneria', null, 'Blinny Lauridsen', null, 'confermato'),
 ('BTHSLV73E146V1TN', 'Sylvan', 'Bethel', '1973-05-14', 'SUPERIOR', 'pieno', 'ricercatore', 'laurea', 'Insituto Universitario - Centro Latinoamericano de Economia Humana - IU Claeh', 'Architettura',86, null, null, 'confermato'),
 ('STFDTO92B24QNZDD', 'Dot', 'Staff', '1992-02-24', 'SCRANTON', 'pieno', 'professore', 'laurea', 'E.A.P. Europäische Wirtschaftshochschule Berlin', 'Economia',75, null, 'seconda', null),
 ('WLSSIA84E47CYZTU', 'Isa', 'Walster', '1984-05-07', 'MUNISING', 'parziale', 'ricercatore', 'laurea', 'Paktia University', 'Psicologia',68, null, null, 'non confermato'),
 ('DVSDPH79C02AXLSC', 'Adolpho', 'Davis', '1979-03-02', 'GUNTERSVILLE', 'pieno', 'professore', 'laurea', 'Loyola Marymount University', 'Filosofia',79, null, 'seconda', null),
 ('RYLBNT80L28C3EKG', 'Bernette', 'Rylance', '1980-07-28', 'ST JOHNSBURY', 'parziale', 'ricercatore', 'laurea', 'Kent State University - Tuscarawas', 'Scienze Politiche',89, null, null, 'non confermato'),
 ('CHLMRO61E26K8LJG', 'Moore', 'Chilton', '1961-05-26', 'MILWAUKEE', 'pieno', 'professore', 'dottorato di ricerca', 'Université Kofi Annan', 'Informatica', null, 'Moore Chilton', 'prima', null),
 ('MRBMLY93M11SSIBS', 'Molly', 'Morby', '1993-08-11', 'TROY', 'pieno', 'professore', 'dottorato di ricerca', 'Chiang Mai University', 'Matematica', null, 'Molly Morby', 'prima', null),
 ('PRVSNE90R46LJ4DZ', 'Seana', 'Purvess', '1990-10-06', 'CINCINNATI', 'parziale', 'professore', 'laurea', 'Waterford Institute Of Technology', 'Fisica',96, null, 'seconda', null),
 ('SYKWLT88C20PUDYW', 'Wilt', 'Sykes', '1988-03-20', 'ALBANY', 'parziale', 'ricercatore', 'laurea', 'Universidade Estadual de Campinas', 'Medicina',73, null, null, 'confermato'),
 ('LMSCRR62S05ZU2FR', 'Curr', 'Lumsdall', '1962-11-05', 'HICKMAN', 'parziale', 'professore', 'laurea', 'Technion - Israel Institute of Technology', 'Ingegneria',79, null, 'seconda', null),
 ('BLTGAE88E18KHO4Z', 'Gae', 'Boulter', '1988-05-18', 'LOS ANGELES', 'pieno', 'professore', 'laurea', 'Atlanta College of Art', 'Architettura',71, null, 'seconda', null),
 ('FRRNST73A59YXX8V', 'Nesta', 'Forrestill', '1973-01-19', 'SHENANDOAH', 'pieno', 'professore', 'dottorato di ricerca', 'Sabaragamuwa University of Sri Lanka', 'Economia', null, 'Nesta Forrestill', 'prima', null),
 ('DWSLRK70S62TPFCW', 'Ulrika', 'Dewsbury', '1970-11-22', 'MIAMI', 'parziale', 'ricercatore', 'laurea', 'Lincoln University', 'Psicologia',108, null, null, 'confermato'),
 ('CNSMRL66P23KC6SR', 'Merl', 'Cansdill', '1966-09-23', 'ROCHESTER', 'pieno', 'ricercatore', 'dottorato di ricerca', 'University of Wroclaw', 'Filosofia', null, 'Merl Cansdill', null, 'non confermato'),
 ('JLNNKL69H52YE5AZ', 'Nikolia', 'Julian', '1969-06-12', 'MIDLAND', 'parziale', 'professore', 'dottorato di ricerca', 'Berklee College of Music', 'Scienze Politiche', null, 'Nikolia Julian', 'prima', null),
 ('GLVMRL83P09FUCHJ', 'Murial', 'Ogilvie', '1983-09-09', 'BONITA', 'pieno', 'ricercatore', 'dottorato di ricerca', 'State University of New York at Binghamton', 'Informatica', null, 'Murial Ogilvie', null, 'non confermato'),
 ('GTSLRI76M16825TC', 'Ilario', 'Gitsham', '1976-08-16', 'BROOKLYN', 'parziale', 'professore', 'dottorato di ricerca', 'Augusta State University', 'Matematica', null, 'Ilario Gitsham', 'seconda', null),
 ('MPYLND70E28E8DWF', 'Lynde', 'Impy', '1970-05-28', 'MIAMI', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Rockhurst College', 'Fisica', null, 'Lynde Impy', null, 'confermato'),
 ('BSNRWN70R21BZWZC', 'Rowan', 'Beasant', '1970-10-21', 'WATERLOO', 'parziale', 'professore', 'dottorato di ricerca', 'Islamic University of Technology', 'Medicina', null, 'Rowan Beasant', 'prima', null),
 ('MNTBTR72L22D7TDL', 'Bartram', 'Manthroppe', '1972-07-22', 'MASSENA', 'pieno', 'professore', 'dottorato di ricerca', 'Sugino Women''s College', 'Ingegneria', null, 'Bartram Manthroppe', 'prima', null),
 ('GBBBRT64P582GCZE', 'Brita', 'Gibbings', '1964-09-18', 'OCEANSIDE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'City University of New York, York College', 'Architettura', null, 'Brita Gibbings', null, 'confermato'),
 ('NTSCLN80S20WF6ZD', 'Carolin', 'Antosch', '1980-11-20', 'ALACHUA', 'parziale', 'ricercatore', 'laurea', 'Rust College', 'Economia',92, null, null, 'non confermato'),
 ('BRSSSM64S09N9P2E', 'Sigismundo', 'Briscoe', '1964-11-09', 'CLAREMORE', 'pieno', 'professore', 'laurea', 'The College of St. Scholastica', 'Psicologia',80, null, 'seconda', null),
 ('HRBCRT70H54I0J4Y', 'Charita', 'Harbisher', '1970-06-14', 'FRANKLIN', 'pieno', 'professore', 'laurea', 'Stamford International University', 'Filosofia',88, null, 'prima', null),
 ('BLNMRC73H09OPDSC', 'Marcie', 'Blanque', '1973-06-09', 'HOOKSETT', 'parziale', 'professore', 'dottorato di ricerca', 'Open University of Sudan (OUS)', 'Scienze Politiche', null, 'Marcie Blanque', 'seconda', null),
 ('KRSDTT86L09H17OE', 'Odette', 'Kares', '1986-07-09', 'LAKE CHARLES', 'pieno', 'ricercatore', 'laurea', 'Universidad del Centro de México', 'Informatica',98, null, null, 'confermato'),
 ('GNTCHN84P11OMCRB', 'Chen', 'Gauntley', '1984-09-11', 'MIAMI', 'parziale', 'ricercatore', 'laurea', 'Paine College', 'Matematica',89, null, null, 'confermato'),
 ('TRRGPR81B28UOH7P', 'Gasparo', 'Terrey', '1981-02-28', 'WASHINGTON', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Silpakorn University', 'Fisica', null, 'Gasparo Terrey', null, 'non confermato'),
 ('SNTMRV86B19CL84Z', 'Merv', 'Osant', '1986-02-19', 'LEBANON', 'parziale', 'professore', 'laurea', 'Fachhochschule Mainz', 'Medicina',93, null, 'prima', null),
 ('GYNJNN75C25T7VYU', 'Janine', 'Gaynes', '1975-03-25', 'PLANTATION', 'parziale', 'professore', 'dottorato di ricerca', 'Stavropol State University', 'Ingegneria', null, 'Janine Gaynes', 'seconda', null),
 ('CLBLNR73A51GELFM', 'Elnora', 'Calbert', '1973-01-11', 'PINEVILLE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Turkish Naval Academy', 'Architettura', null, 'Elnora Calbert', null, 'confermato'),
 ('PTTLLE93S26KRPGY', 'Euell', 'Patty', '1993-11-26', 'STATE COLLEGE', 'parziale', 'ricercatore', 'laurea', 'Institut National des Sciences Appliquées de Toulouse', 'Economia',104, null, null, 'confermato'),
 ('FRLKTN94A55QK5TV', 'Katina', 'Farlambe', '1994-01-15', 'ROSEVILLE', 'parziale', 'ricercatore', 'laurea', 'Ecole Supérieure de Chimie Physique Electronique de Lyon', 'Psicologia',95, null, null, 'non confermato'),
 ('DRSDMN74L14UD6VN', 'Desmund', 'Drust', '1974-07-14', 'VICTORIA', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Union College Kentucky', 'Filosofia', null, 'Desmund Drust', null, 'confermato'),
 ('PCKRKY94M17QIG5M', 'Rockey', 'Pouck', '1994-08-17', 'OAKLAND PARK,', 'parziale', 'professore', 'dottorato di ricerca', 'Kuban State University', 'Scienze Politiche', null, 'Rockey Pouck', 'prima', null),
 ('STNKGS78A25JJ5KY', 'Kingsly', 'Easton', '1978-01-25', 'OAKLAND', 'parziale', 'professore', 'dottorato di ricerca', 'Ecole Nationale d''Ingénieurs de Metz', 'Informatica', null, 'Kingsly Easton', 'prima', null),
 ('CRSCND93M28IYN1O', 'Candi', 'Crees', '1993-08-28', 'BOCA RATON', 'pieno', 'ricercatore', 'laurea', 'Universidad de Viña del Mar', 'Matematica',86, null, null, 'confermato'),
 ('LGRTBO88P30N2FVL', 'Tobie', 'Algar', '1988-09-30', 'MIAMI', 'parziale', 'ricercatore', 'laurea', 'Texas Woman''s University', 'Fisica',105, null, null, 'non confermato'),
 ('HRTLND83T29TP96Y', 'Leonid', 'Hartburn', '1983-12-29', 'DENVER', 'pieno', 'professore', 'dottorato di ricerca', 'Universidade do Algarve', 'Medicina', null, 'Leonid Hartburn', 'seconda', null),
 ('QNTKND63E31FR70H', 'Kennedy', 'Quinton', '1963-05-31', 'CHARLOTTE', 'parziale', 'professore', 'dottorato di ricerca', 'Technological University (Monywa)', 'Ingegneria', null, 'Kennedy Quinton', 'prima', null),
 ('STWGRA86L053NNWA', 'Gar', 'Stawell', '1986-07-05', 'BOCA RATON', 'pieno', 'ricercatore', 'laurea', 'Instituto Nacional de Matemática Pura e Aplicada - IMPA', 'Architettura',97, null, null, 'confermato'),
 ('TRWVRN94H68T0LLX', 'Verina', 'Trowl', '1994-06-28', 'OAKES', 'pieno', 'ricercatore', 'laurea', 'Beijing International Studies University', 'Economia',66, null, null, 'non confermato'),
 ('MLNVNY87C18EQIGD', 'Vinny', 'Emeline', '1987-03-18', 'DEARBORN', 'pieno', 'professore', 'dottorato di ricerca', 'College of Notre Dame', 'Psicologia', null, 'Vinny Emeline', 'seconda', null),
 ('MBBWDO77S18YXINK', 'Wood', 'Mabbutt', '1977-11-18', 'LONGVIEW', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad Nacional de Tucumán', 'Filosofia', null, 'Wood Mabbutt', 'seconda', null),
 ('SNKDFF92P203RR7S', 'Daffie', 'Sinkins', '1992-09-20', 'HERSHEY', 'parziale', 'ricercatore', 'laurea', 'Trinity University', 'Scienze Politiche',86, null, null, 'non confermato'),
 ('DDLLNN67D30UZI4B', 'Linnie', 'Dudley', '1967-04-30', 'KEENE', 'parziale', 'professore', 'dottorato di ricerca', 'Bond University', 'Informatica', null, 'Linnie Dudley', 'seconda', null),
 ('SCKMML86S14VVASB', 'Maximilianus', 'Sickamore', '1986-11-14', 'BURKESVILLE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Universitas Wijaya Kusuma Purwokerto', 'Matematica', null, 'Maximilianus Sickamore', null, 'confermato'),
 ('HYMCLT70T5354T1V', 'Carlota', 'Hyman', '1970-12-13', 'PHOENIX', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Kenyatta University', 'Fisica', null, 'Carlota Hyman', null, 'confermato'),
 ('BSHMTG85H60KEOJZ', 'Martguerita', 'Bosher', '1985-06-20', 'FT CAVAZOS', 'parziale', 'professore', 'dottorato di ricerca', 'Texas Wesleyan University', 'Medicina', null, 'Martguerita Bosher', 'seconda', null),
 ('NSMCSS94D56G51RT', 'Corissa', 'Neesam', '1994-04-16', 'SOUTH MIAMI', 'parziale', 'professore', 'dottorato di ricerca', 'University of South Alabama', 'Ingegneria', null, 'Corissa Neesam', 'seconda', null),
 ('JFFRLD77E07IYMNI', 'Arnaldo', 'Jaffray', '1977-05-07', 'MISSOULA', 'parziale', 'ricercatore', 'laurea', 'Balkh University', 'Architettura',66, null, null, 'confermato'),
 ('MCNCRY86A080QN6Q', 'Carey', 'McEntegart', '1986-01-08', 'WINFIELD', 'pieno', 'ricercatore', 'laurea', 'Fachhochschule Heilbronn, Hochschule für Technik und Wirtschaft', 'Economia', 99, null, null, 'non confermato'),
 ('KLHLNY94H109BFJL', 'Lanny', 'Kleehuhler', '1994-06-10', 'BILOXI', 'pieno', 'ricercatore', 'laurea', 'Institute of Paper Science and Technology', 'Psicologia',76, null, null, 'non confermato'),
 ('FRMMRY86M20PD9PY', 'Emery', 'Foreman', '1986-08-20', 'WINTER PARK', 'pieno', 'ricercatore', 'laurea', 'Istanbul Arel University', 'Filosofia',67, null, null, 'non confermato'),
 ('KRNNRY92D15ZY0UX', 'Norry', 'Kornilov', '1992-04-15', 'SAN FRANCISCO', 'pieno', 'ricercatore', 'laurea', 'Japan College of Social Work', 'Scienze Politiche',76, null, null, 'confermato'),
 ('BLDMYL68E2156FRP', 'Meryl', 'Bladen', '1968-05-21', 'BELZONI', 'pieno', 'professore', 'dottorato di ricerca', 'Université des Montagnes', 'Informatica', null, 'Meryl Bladen', 'seconda', null),
 ('CRBTMO61L30YQJGV', 'Tome', 'Corbet', '1961-07-30', 'PORTLAND', 'parziale', 'professore', 'laurea', 'Oakwood College', 'Matematica',86, null, 'prima', null),
 ('SRGBKL91A08I02BH', 'Berkeley', 'Sargint', '1991-01-08', 'FORT HOOD', 'pieno', 'ricercatore', 'laurea', 'Universitas Klabat', 'Fisica',92, null, null, 'confermato'),
 ('THRNNA68A016PUUI', 'Anne', 'Thurgood', '1968-01-01', 'MASON CITY', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Nigde University', 'Medicina', null, 'Anne Thurgood', null, 'non confermato'),
 ('MDDNMO71R01BWU3J', 'Nomi', 'Maddin', '1971-10-01', 'BILOXI', 'pieno', 'professore', 'laurea', 'Universidad Pedagógica Nacional, Unidad León', 'Ingegneria', 71, null, 'prima', null),
 ('RSKWTT77P02GENRZ', 'Wittie', 'Reisk', '1977-09-02', 'SPOKANE VALLEY', 'pieno', 'professore', 'laurea', 'Xavier University', 'Architettura',71, null, 'prima', null),
 ('SNELTI74L637LHGA', 'Lita', 'Sein', '1974-07-23', 'ARKANSAS CITY', 'pieno', 'professore', 'laurea', 'Yaroslavl State Pedagogical University', 'Economia',106, null, 'prima', null),
 ('VNLRNN89C2934P8J', 'Reamonn', 'Ivanilov', '1989-03-29', 'CHARLOTTE', 'parziale', 'professore', 'laurea', 'University of Michigan - Dearborn', 'Psicologia',87, null, 'seconda', null),
 ('BNNSHA79E28M2YCG', 'Shae', 'Bannister', '1979-05-28', 'HIALEAH', 'parziale', 'professore', 'laurea', 'Dicle (Tirgris)', 'Filosofia', 83, null, 'prima', null),
 ('MCCJMN89T19Z06OG', 'Jasmin', 'McCorkell', '1989-12-19', 'CLEARFIELD', 'parziale', 'professore', 'laurea', 'Universidad de Medellín', 'Scienze Politiche',89, null, 'prima', null),
 ('DYSKLK86M1433WWZ', 'Karlik', 'Dyas', '1986-08-14', 'FLAGSTAFF', 'parziale', 'ricercatore', 'dottorato di ricerca', 'University of Art and Design Helsinki', 'Informatica', null, 'Karlik Dyas', null, 'confermato'),
 ('STTGLL82R30R94ZJ', 'Gill', 'Stitson', '1982-10-30', 'DETROIT', 'pieno', 'professore', 'dottorato di ricerca', 'Nukus State Teachers Training Institute', 'Matematica', null, 'Gill Stitson', 'seconda', null),
 ('BTTKRR68E61Q096H', 'Klarrisa', 'Butterick', '1968-05-21', 'MIAMI', 'pieno', 'professore', 'dottorato di ricerca', 'Universidade Castelo Branco', 'Fisica', null, 'Klarrisa Butterick', 'seconda', null),
 ('DCRGTT73P66XQ4LT', 'Giuditta', 'De Carlo', '1973-09-26', 'MANATI', 'parziale', 'professore', 'dottorato di ricerca', 'Saigon University', 'Medicina', null, 'Giuditta De Carlo', 'seconda', null),
 ('LBNHMD85M48DL32H', 'Halimeda', 'Alibone', '1985-08-08', 'MIDLAND', 'pieno', 'ricercatore', 'laurea', 'Southwest University', 'Ingegneria',102, null, null, 'confermato'),
 ('SLLDHA70P30FCS2W', 'Adah', 'Sillitoe', '1970-09-30', 'HARRISON', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad Chapultepéc', 'Architettura', null, 'Adah Sillitoe', 'prima', null),
 ('CRNDTH85L4432JII', 'Editha', 'Cornfield', '1985-07-04', 'RANCHO CUCAMONGA', 'parziale', 'professore', 'laurea', 'Arba Minch University', 'Economia',95, null, 'seconda', null),
 ('PNCKGS65A21N2O7W', 'Kingsley', 'Pauncefoot', '1965-01-21', 'INDIANAPOLIS', 'pieno', 'professore', 'laurea', 'Norwegian University of Life Sciences', 'Psicologia',69, null, 'prima', null),
 ('CHNCHD93A085S5OR', 'Chad', 'Chanter', '1993-01-08', 'JEMEZ SPRINGS', 'pieno', 'ricercatore', 'laurea', 'California Baptist College', 'Filosofia',109, null, null, 'non confermato'),
 ('TPNGTV82L23HJJJL', 'Gustavo', 'Tapenden', '1982-07-23', 'DURHAM', 'pieno', 'professore', 'dottorato di ricerca', 'Sumy National Agrarian University', 'Scienze Politiche', null, 'Gustavo Tapenden', 'prima', null),
 ('WLBCHL65T02YD1PN', 'Cathleen', 'Welbelove', '1965-12-02', 'HARTFORD', 'pieno', 'ricercatore', 'laurea', 'Université Julius Nyerere Kankan', 'Informatica',81, null, null, 'confermato'),
 ('CRLMRS92E69UY62K', 'Marrissa', 'Carlan', '1992-05-29', 'BURKESVILLE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Fachhochschule Würzburg - Schweinfurt', 'Matematica', null, 'Marrissa Carlan', null, 'confermato'),
 ('MRLRHB74P03JIPYN', 'Archibald', 'Marlor', '1974-09-03', 'NORFOLK', 'pieno', 'professore', 'dottorato di ricerca', 'Montana State University - Billings', 'Fisica', null, 'Archibald Marlor', 'seconda', null),
 ('RBNKRY86R03L1F3H', 'Kerry', 'Raubenheimer', '1986-10-03', 'SNYDER', 'parziale', 'professore', 'dottorato di ricerca', 'Megatrend University of Applied Sciences', 'Medicina', null, 'Kerry Raubenheimer', 'prima', null),
 ('DLEKSS72T46B1K2Z', 'Kessia', 'Deal', '1972-12-06', 'CLINTON TOWNSHIP', 'pieno', 'professore', 'laurea', 'Temple University Japan', 'Ingegneria',107, null, 'prima', null),
 ('DLYSRM62B145PO2U', 'Stormi', 'Dealy', '1962-02-14', 'MAYAGUEZ', 'pieno', 'professore', 'laurea', 'Texas College of Osteopathic Medicine', 'Architettura',103, null, 'prima', null),
 ('SNPMYR85B20TDBQB', 'Meyer', 'Snap', '1985-02-20', 'NEW YORK', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Halla University', 'Economia', null, 'Meyer Snap', null, 'non confermato'),
 ('WRMRTA88A05WSHQZ', 'Artie', 'Warman', '1988-01-05', 'LOUISVILLE', 'parziale', 'ricercatore', 'laurea', 'Brandeis University', 'Psicologia',78, null, null, 'confermato'),
 ('MRLJNV81E52EVRXS', 'Janeva', 'Marlen', '1981-05-12', 'TAMPA', 'parziale', 'professore', 'laurea', 'Shreemati Nathibai Damodar Thackersey Women''s University', 'Filosofia',73, null, 'seconda', null),
 ('BRNTRR92E05CBGFM', 'Torrie', 'Braunroth', '1992-05-05', 'ALBUQUERQUE', 'parziale', 'professore', 'laurea', 'Lycoming College', 'Scienze Politiche',109, null, 'prima', null),
 ('MSDMYL86R16S7ELO', 'Emylee', 'Amsden', '1986-10-16', 'OKLAHOMA CITY', 'parziale', 'ricercatore', 'dottorato di ricerca', 'University of Maryland at College Park', 'Informatica', null, 'Emylee Amsden', null, 'confermato'),
 ('WNSLHT86L0151I7P', 'Leighton', 'Wansbury', '1986-07-01', 'GROESBECK', 'pieno', 'professore', 'laurea', 'Bellevue University', 'Matematica',68, null, 'seconda', null),
 ('MGLCMY88D042FYHO', 'Camey', 'Miguel', '1988-04-04', 'NEW ORLEANS', 'pieno', 'professore', 'dottorato di ricerca', 'Kalinga University', 'Fisica', null, 'Camey Miguel', 'prima', null),
 ('CRMSLY64M21W6H1Z', 'Sallyanne', 'Creamer', '1964-08-21', 'YORK', 'parziale', 'ricercatore', 'laurea', 'International Kazakh-Turkish University', 'Medicina',87, null, null, 'confermato'),
 ('MCGHTR61S12G9IWU', 'Hunter', 'McGillreich', '1961-11-12', 'GUTHRIE CENTER', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad Austral de Chile', 'Ingegneria', null, 'Hunter McGillreich', 'seconda', null),
 ('DMECLR74A2473OMZ', 'Chloris', 'Deme', '1974-01-24', 'TACOMA', 'pieno', 'professore', 'dottorato di ricerca', 'Soochow University', 'Architettura', null, 'Chloris Deme', 'prima', null),
 ('RMOTBR76R26ALPRZ', 'Tabor', 'Romeo', '1976-10-26', 'CLAIRTON', 'parziale', 'professore', 'dottorato di ricerca', 'Ithaca College', 'Economia', null, 'Tabor Romeo', 'seconda', null),
 ('VSOMGG70C03J48OC', 'Maggie', 'Voas', '1970-03-03', 'MIAMI', 'parziale', 'professore', 'laurea', 'The Art Institutes International Portland', 'Psicologia',100, null, 'seconda', null),
 ('BRMRVN75P12YGN5W', 'Raven', 'Bremen', '1975-09-12', 'KEOSAUQUA', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Sichuan University', 'Filosofia', null, 'Raven Bremen', null, 'non confermato'),
 ('LVRKLA80A55PVVYO', 'Kala', 'Lovart', '1980-01-15', 'FORT WAYNE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Université de Yaoundé I', 'Scienze Politiche', null, 'Kala Lovart', null, 'confermato'),
 ('DYMNCL72A30NZS0P', 'Nicol', 'Dymond', '1972-01-30', 'THOMASVILLE', 'parziale', 'ricercatore', 'laurea', 'Chalmers University of Technology', 'Informatica',87, null, null, 'non confermato'),
 ('JLLDNT89S04Z3XVL', 'Durant', 'Jolliff', '1989-11-04', 'NEW YORK', 'parziale', 'professore', 'laurea', 'Universidad Privada Juan Mejía Baca', 'Matematica',82, null, 'prima', null),
 ('STTJKY60A02KJJYT', 'Jacky', 'Stothert', '1960-01-02', 'DALLAS', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Brandon University', 'Fisica', null, 'Jacky Stothert', null, 'non confermato'),
 ('KPPQTS90S20R8A2Q', 'Quintus', 'Kipping', '1990-11-20', 'GULFPORT', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Islamic College for Sciences and Technologies', 'Medicina', null, 'Quintus Kipping', null, 'non confermato'),
 ('WHCDTY92D64ZXMWS', 'Doroteya', 'Whichelow', '1992-04-24', 'BURKESVILLE', 'parziale', 'professore', 'laurea', 'College of Notre Dame of Maryland', 'Ingegneria',107, null, 'prima', null),
 ('GLZPRC83E078Z3FR', 'Perice', 'Glozman', '1983-05-07', 'PAWHUSKA', 'pieno', 'professore', 'laurea', 'Universidad Fray Luca Paccioli', 'Architettura',67, null, 'prima', null),
 ('STNBNY79T31Z0U9H', 'Bonny', 'Stonhouse', '1979-12-31', 'RENTON', 'pieno', 'ricercatore', 'laurea', 'Universiteit Doesburg (UNDO)', 'Economia', 91, null, null, 'non confermato'),
 ('SWNJMM89R29FBAHL', 'Jemmie', 'Swinden', '1989-10-29', 'KAPAAU', 'pieno', 'professore', 'dottorato di ricerca', 'Hodges University', 'Psicologia', null, 'Jemmie Swinden', 'seconda', null),
 ('JRCLYN71D61XRMHW', 'Lynea', 'Jurczyk', '1971-04-21', 'MANASSAS', 'pieno', 'ricercatore', 'laurea', 'Deaconess College of Nursing', 'Filosofia',96, null, null, 'confermato'),
 ('TSTQNT90D53ZZ7LY', 'Quinta', 'Testro', '1990-04-13', 'TULSA', 'pieno', 'professore', 'dottorato di ricerca', 'Fachhochschule für die Wirtschaft', 'Scienze Politiche', null, 'Quinta Testro', 'prima', null),
 ('CCHNYA88B49FB1PD', 'Anya', 'Coucha', '1988-02-09', 'PURCELL', 'parziale', 'professore', 'dottorato di ricerca', 'University of Technology Sydney', 'Informatica', null, 'Anya Coucha', 'prima', null),
 ('HNDCRL86S03TMWKI', 'Carlie', 'Hundell', '1986-11-03', 'DETROIT', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Pace University  Pleasantville/Briarcliff', 'Matematica', null, 'Carlie Hundell', null, 'confermato'),
 ('GLLNDE88L11TG23D', 'Ned', 'Gillcrist', '1988-07-11', 'MERIDIAN', 'parziale', 'professore', 'dottorato di ricerca', 'Islamic Azad University, Bojnourd', 'Fisica', null, 'Ned Gillcrist', 'prima', null),
 ('SMLWHT60C07IA3EA', 'Whit', 'Smallsman', '1960-03-07', 'NOCONA', 'parziale', 'ricercatore', 'laurea', 'University of Illinois at Springfield', 'Medicina',70, null, null, 'confermato'),
 ('DCLPSY64M17JFMLY', 'Pansy', 'Di Claudio', '1964-08-17', 'DALLAS', 'parziale', 'professore', 'dottorato di ricerca', 'Benedict College', 'Ingegneria', null, 'Pansy Di Claudio', 'prima', null),
 ('GJRNBL88B563K1NE', 'Annabela', 'Gjerde', '1988-02-16', 'HOLLYWOOD', 'parziale', 'professore', 'dottorato di ricerca', 'Universität Mannheim', 'Architettura', null, 'Annabela Gjerde', 'seconda', null),
 ('MCQMRG85H13L7N1H', 'Margo', 'McQuie', '1985-06-13', 'ASHLAND', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Universidade Federal Rural de Pernambuco', 'Economia', null, 'Margo McQuie', null, 'non confermato'),
 ('VNWWDL93E137B7XC', 'Wendeline', 'Von Welden', '1993-05-13', 'KINGSTON', 'parziale', 'professore', 'dottorato di ricerca', 'Estonian Business School', 'Psicologia', null, 'Wendeline Von Welden', 'prima', null),
 ('WHPCTA74H07HN6OU', 'Cati', 'Whapples', '1974-06-07', 'MUSKEGON', 'parziale', 'ricercatore', 'laurea', 'Beijing Polytechnic University', 'Filosofia',108, null, null, 'non confermato'),
 ('LVLCMN68B19QYVOR', 'Clemens', 'Liveley', '1968-02-19', 'HUDSON', 'pieno', 'professore', 'dottorato di ricerca', 'University of Aviation and Technology', 'Scienze Politiche', null, 'Clemens Liveley', 'seconda', null),
 ('GLLCLY90B28S9F8F', 'Cally', 'Gallgher', '1990-02-28', 'ROCK PORT', 'pieno', 'ricercatore', 'laurea', 'West Bengal University of Animal and Fishery Sciences', 'Informatica',110, null, null, 'confermato'),
 ('BLBSMA61E03LQDWD', 'Sam', 'Bielby', '1961-05-03', 'JOHNSON CITY', 'parziale', 'professore', 'dottorato di ricerca', 'Shiraz University of Medical Sciences', 'Matematica', null, 'Sam Bielby', 'prima', null),
 ('DMEDTH80R65LP2QR', 'Dorothea', 'Deem', '1980-10-25', 'BINGHAMTON', 'parziale', 'professore', 'laurea', 'Karwan Institute of Higher Education', 'Fisica',72, null, 'seconda', null),
 ('HNRBTT72B05WJE4G', 'Britteny', 'Hinrich', '1972-02-05', 'LOUISVILLE', 'parziale', 'professore', 'laurea', 'Fachhochschule Hildesheim/Holzminden/Göttingen, Hochschule für angewandte Wissenschaft und Kunst', 'Medicina', 88,null, 'prima', null),
 ('NWKTMK88E24OP5BV', 'Tamiko', 'Nowakowska', '1988-05-24', 'CLAIRTON', 'parziale', 'professore', 'laurea', 'Western Kentucky University', 'Ingegneria',87, null, 'seconda', null),
 ('RSTNLL63B02NJAFI', 'Noll', 'Restall', '1963-02-02', 'LAFAYETTE', 'pieno', 'professore', 'laurea', 'Guangxi Traditional Chinese Medical University', 'Architettura',78, null, 'seconda', null),
 ('SRGBBE86P168RZQK', 'Bebe', 'Sargant', '1986-09-16', 'HOLLISTER', 'pieno', 'ricercatore', 'laurea', 'Université d''Abobo-Adjamé', 'Economia',89, null, null, 'confermato'),
 ('LLSHFR88S17TTLDP', 'Humfrid', 'Ellsom', '1988-11-17', 'ONEONTA', 'parziale', 'professore', 'laurea', 'Chadron State College', 'Psicologia',73, null, 'prima', null),
 ('SMTDWY85B15Y68PG', 'Dewey', 'Smeaton', '1985-02-15', 'OAK FOREST', 'pieno', 'professore', 'laurea', 'Universidad Mariano Egaña', 'Filosofia',81, null, 'seconda', null),
 ('BSSMHL75R048FYMT', 'Michail', 'Bussetti', '1975-10-04', 'CHARLOTTE', 'pieno', 'professore', 'laurea', 'Franklin Pierce College', 'Scienze Politiche',94, null, 'seconda', null),
 ('HMBGRT70P22QF54C', 'Grete', 'Hambidge', '1970-09-22', 'DALLAS', 'parziale', 'professore', 'laurea', 'Indiana State University', 'Informatica',76, null, 'prima', null),
 ('FRDRRQ86D09BBAPF', 'Rodrique', 'Fereday', '1986-04-09', 'MUNISING', 'parziale', 'professore', 'laurea', 'Future University', 'Matematica',73, null, 'prima', null),
 ('HNSRYS66P09HJZPD', 'Rhys', 'Haines', '1966-09-09', 'CHARLOTTE', 'parziale', 'ricercatore', 'laurea', 'Ecole Nationale Vétérinaire de Lyon', 'Fisica',80, null, null, 'confermato'),
 ('LLWCLY65A27WKUYB', 'Carolyne', 'Llewelly', '1965-01-27', 'FRANKLIN', 'pieno', 'professore', 'dottorato di ricerca', 'Allahabad University', 'Medicina', null, 'Carolyne Llewelly', 'seconda', null),
 ('RYSRGS65C15BDQHK', 'Iorgos', 'Ryson', '1965-03-15', 'LAKE ISABELLA', 'parziale', 'ricercatore', 'laurea', 'Teachers College, Columbia University', 'Ingegneria', 101, null, null, 'non confermato'),
 ('GLDCVR73P18ICN2K', 'Carver', 'Gladeche', '1973-09-18', 'GENESEO', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Lancaster Bible College', 'Architettura', null, 'Carver Gladeche', null, 'non confermato'),
 ('STYRLY85H29T5C4N', 'Early', 'Staynes', '1985-06-29', 'HUEYTOWN', 'parziale', 'ricercatore', 'dottorato di ricerca', 'National Dong Hwa University', 'Economia', null, 'Early Staynes', null, 'confermato'),
 ('DCHVVK65E04WLCUX', 'Vidovik', 'Diche', '1965-05-04', 'BRIARWOOD', 'pieno', 'professore', 'laurea', 'University of California, San Francisco', 'Psicologia', 104, null, 'prima', null),
 ('XLAFRD60C282RC1P', 'Ferdie', 'Axel', '1960-03-28', 'LOUISVILLE', 'parziale', 'professore', 'laurea', 'Medical Academy in Gdansk', 'Filosofia',96, null, 'seconda', null),
 ('STLCDY78P17I1USJ', 'Cody', 'Stolle', '1978-09-17', 'MOUNT CARMEL', 'pieno', 'ricercatore', 'dottorato di ricerca', 'King Abdul Aziz University', 'Scienze Politiche', null, 'Cody Stolle', null, 'non confermato'),
 ('LDLMRA81S30O0ZVL', 'Maurie', 'Ladell', '1981-11-30', 'MILWAUKEE', 'pieno', 'ricercatore', 'laurea', 'Anadolu University', 'Informatica',79, null, null, 'confermato'),
 ('HYANKI78D23SSUSY', 'Niki', 'Hay', '1978-04-23', 'NASHVILLE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Universidad Técnica de Babahoyo', 'Matematica', null, 'Niki Hay', null, 'confermato'),
 ('CNSRNY62E22SSF7O', 'Rowney', 'Cansdall', '1962-05-22', 'LAWRENCE', 'pieno', 'ricercatore', 'laurea', 'Buena Vista University', 'Fisica',98, null, null, 'non confermato'),
 ('BRFRBN69A61ER03Q', 'Robenia', 'Burford', '1969-01-21', 'LOS ANGELES', 'pieno', 'ricercatore', 'laurea', 'Göteborg University', 'Medicina',73, null, null, 'non confermato'),
 ('RXETKY88C21S0HIB', 'Tucky', 'Rex', '1988-03-21', 'LAFAYETTE', 'parziale', 'ricercatore', 'laurea', 'Kherson State University', 'Ingegneria',94, null, null, 'confermato'),
 ('CHSMNM92D23P5S3T', 'Minnaminnie', 'Chesswas', '1992-04-23', 'NEWARK', 'pieno', 'professore', 'laurea', 'American World University', 'Architettura',72, null, 'seconda', null),
 ('WRTCSM90E209FZFE', 'Cosimo', 'Wortt', '1990-05-20', 'FORT STEWART', 'pieno', 'ricercatore', 'laurea', 'Chiba Keizai University', 'Economia',77, null, null, 'non confermato'),
 ('PDRKTT68E28LFSSU', 'Kittie', 'Padrick', '1968-05-28', 'EDMONDS', 'pieno', 'professore', 'laurea', 'Appalachian State University', 'Psicologia',68, null, 'prima', null),
 ('MCGGFL60T11PT3FI', 'Garfield', 'McGrotty', '1960-12-11', 'ARCO', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Katharine Gibbs School', 'Filosofia', null, 'Garfield McGrotty', null, 'non confermato'),
 ('MCRPNC75C22KM6PT', 'Prince', 'MacRorie', '1975-03-22', 'AKRON', 'parziale', 'ricercatore', 'laurea', 'Park College', 'Scienze Politiche',90, null, null, 'confermato'),
 ('GRGTSO85R163MBTO', 'Oates', 'Grieger', '1985-10-16', 'SAN ANTONIO', 'pieno', 'professore', 'laurea', 'Fachhochschule Bonn-Rhein-Sieg', 'Informatica',86, null, 'prima', null),
 ('BTTVYN74T11LA0MV', 'Evelyn', 'Botterill', '1974-12-11', 'WENATCHEE', 'pieno', 'professore', 'laurea', 'Universidad Nacional de Santiago del Estero', 'Matematica',107, null, 'prima', null),
 ('HCQBNN83S25Q7EQH', 'Binni', 'Hacquoil', '1983-11-25', 'GREEN BAY', 'pieno', 'ricercatore', 'laurea', 'Sugino Women''s College', 'Fisica',109, null, null, 'non confermato'),
 ('MRTCTT90R284KWYE', 'Corette', 'Martello', '1990-10-28', 'MIAMI', 'parziale', 'professore', 'dottorato di ricerca', 'Koforidua Polytechnic ', 'Medicina', null, 'Corette Martello', 'seconda', null),
 ('BTTCRN78H276CCRM', 'Caron', 'Bettenson', '1978-06-27', 'MERIDIAN', 'pieno', 'ricercatore', 'laurea', 'Hochschule für Technik und Wirtschaft Dresden (FH)', 'Ingegneria', 110, null, null, 'non confermato'),
 ('SYBSVR68S02EXR2I', 'Stavros', 'Sybry', '1968-11-02', 'ATLANTA', 'pieno', 'professore', 'dottorato di ricerca', 'Marietta College', 'Architettura', null, 'Stavros Sybry', 'prima', null),
 ('DNEKNN88S05DBQBL', 'Keriann', 'Edon', '1988-11-05', 'DALLAS', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Universidad de Sonora', 'Economia', null, 'Keriann Edon', null, 'confermato'),
 ('MCKJLN67R03ZB5FK', 'Jillene', 'McKenney', '1967-10-03', 'CLINTON', 'parziale', 'professore', 'laurea', 'Belarussian State University of Culture and Arts', 'Psicologia',74, null, 'seconda', null),
 ('CLLCHR89H15245YF', 'Cthrine', 'Collyear', '1989-06-15', 'ASHEVILLE', 'pieno', 'professore', 'dottorato di ricerca', 'Virginia Union University', 'Filosofia', null, 'Cthrine Collyear', 'prima', null),
 ('LSTHSH76H247HDLX', 'Hamish', 'Elster', '1976-06-24', 'SEYMOUR', 'pieno', 'ricercatore', 'laurea', 'Northeastern University', 'Scienze Politiche',95, null, null, 'confermato'),
 ('WDRLNN88D05ZLBVU', 'Laurianne', 'Wooderson', '1988-04-05', 'POMEROY', 'pieno', 'professore', 'laurea', 'Al-Manar University', 'Informatica',75, null, 'seconda', null),
 ('BRFGBA85A27IVDZZ', 'Gabi', 'Brafield', '1985-01-27', 'SOUTHFIELD', 'parziale', 'ricercatore', 'laurea', 'Wenzhou Medical College', 'Matematica',92, null, null, 'confermato'),
 ('CHLSBI73E16NKXQT', 'Isabeau', 'Chalkly', '1973-05-16', 'HAMPTON', 'pieno', 'ricercatore', 'laurea', 'Amirkabir University of Technology', 'Fisica',68, null, null, 'confermato'),
 ('PLACRS75R68XL36V', 'Clerissa', 'Paulou', '1975-10-28', 'CUMBERLAND', 'parziale', 'professore', 'laurea', 'Weber State University', 'Medicina',67, null, 'prima', null),
 ('PTTHMD82E161KKCU', 'Hammad', 'Pettegree', '1982-05-16', 'MIAMI', 'pieno', 'professore', 'laurea', 'Universidade do Estado do Rio de Janeiro', 'Ingegneria',83, null, 'prima', null),
 ('SPFLNO86C12SY8II', 'Loni', 'Spafford', '1986-03-12', 'DENVER', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Zhongnan University of Economics and Law', 'Architettura', null, 'Loni Spafford', null, 'confermato'),
 ('DKSNRY82L1976UNY', 'Norry', 'Deakes', '1982-07-19', 'UPLAND', 'pieno', 'ricercatore', 'laurea', 'Universidad de La Frontera', 'Economia',75, null, null, 'confermato'),
 ('RNBCNY90H28PXZ9Z', 'Carney', 'Rainbird', '1990-06-28', 'ARCHIE', 'parziale', 'professore', 'laurea', 'Catholic Theological Union', 'Psicologia',92, null, 'prima', null),
 ('CWOCLE91R7092HUA', 'Clea', 'Cow', '1991-10-30', 'BATON ROUGE', 'parziale', 'professore', 'dottorato di ricerca', 'Ross University Caribbean School of Veterinary Medicine', 'Filosofia', null, 'Clea Cow', 'prima', null),
 ('TLHSTT71T08VCFEP', 'Smitty', 'Tolhurst', '1971-12-08', 'LOVELAND', 'parziale', 'ricercatore', 'laurea', 'Technische Fachhochschule Georg Agricola für Rohstoff, Energie und, Umwelt zu Bochum', 'Scienze Politiche', 96, null, null, 'non confermato'),
 ('MRTCNL68M09JJVVE', 'Cornelius', 'Murt', '1968-08-09', 'WINDSOR', 'parziale', 'professore', 'dottorato di ricerca', 'Kyoto Prefectural University', 'Informatica', null, 'Cornelius Murt', 'prima', null),
 ('LRSRLL89P01MRH0Q', 'Roselle', 'Larose', '1989-09-01', 'CARROLL', 'parziale', 'ricercatore', 'laurea', 'University of Pecs', 'Matematica',105, null, null, 'confermato'),
 ('FRNMKY60H25WOA3U', 'Micky', 'Fernao', '1960-06-25', 'WINSTON SALEM', 'parziale', 'ricercatore', 'laurea', 'Universitas Darma Agung', 'Fisica',84, null, null, 'non confermato'),
 ('JRRDRU80P090KCNE', 'Dur', 'Jorry', '1980-09-09', 'ALBUQUERQUE', 'parziale', 'professore', 'dottorato di ricerca', 'British Columbia Institute of Technology', 'Medicina', null, 'Dur Jorry', 'prima', null),
 ('MCKRDR61H12ZST3F', 'Reidar', 'Muckle', '1961-06-12', 'CAMBRIDGE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Universidad Tecnologica "Vicente Perez Rosales"', 'Ingegneria', null, 'Reidar Muckle', null, 'confermato'),
 ('TRNCMN90R07RPBQW', 'Clemens', 'Trendle', '1990-10-07', 'LENOIR', 'parziale', 'ricercatore', 'laurea', 'Dokuz Eylül University', 'Architettura',96, null, null, 'confermato'),
 ('WHNBHN70M26JB47D', 'Abrahan', 'Whinray', '1970-08-26', 'EDGEWOOD', 'pieno', 'ricercatore', 'laurea', 'Gwangju Catholic College', 'Economia',109, null, null, 'confermato'),
 ('GRLRGN85D16X97BE', 'Regine', 'Gerler', '1985-04-16', 'SAN DIEGO', 'pieno', 'professore', 'dottorato di ricerca', 'National Institute of Industrial Engineering', 'Psicologia', null, 'Regine Gerler', 'prima', null),
 ('JLYJLY67E11EJBQH', 'Joellyn', 'Julyan', '1967-05-11', 'ONEONTA', 'pieno', 'professore', 'dottorato di ricerca', 'European University', 'Filosofia', null, 'Joellyn Julyan', 'seconda', null),
 ('MCGGLN61M03ZD29R', 'Galen', 'McGillacoell', '1961-08-03', 'AMERICAN FORK', 'pieno', 'ricercatore', 'laurea', 'University Vitez In Travnik', 'Scienze Politiche',92, null, null, 'non confermato'),
 ('PRMTMO78A10PSR5D', 'Tomi', 'Paireman', '1978-01-10', 'WATSEKA', 'parziale', 'professore', 'laurea', 'Kazan State University of Medicine', 'Informatica',87, null, 'seconda', null),
 ('LNDTTE83P304232G', 'Etti', 'Lindenstrauss', '1983-09-30', 'CANAJOHARIE', 'parziale', 'professore', 'laurea', 'Institute of Architecture "Ion Mincu" Bucharest', 'Matematica',102, null, 'prima', null),
 ('MCKWST60C05MS9ZA', 'Webster', 'McKniely', '1960-03-05', 'PHILADELPHIA', 'pieno', 'professore', 'laurea', 'China University of Geoscience Beijing', 'Fisica',91, null, 'prima', null),
 ('CRGSME78M14LUV7P', 'Esme', 'Creggan', '1978-08-14', 'ROCKVILLE CENTRE', 'parziale', 'ricercatore', 'dottorato di ricerca', 'Oklahoma State University Center for Health Sciences', 'Medicina', null, 'Esme Creggan', null, 'non confermato'),
 ('KNDTBR65H10DNDTI', 'Tabor', 'Kendell', '1965-06-10', 'CHICAGO HEIGHTS', 'pieno', 'ricercatore', 'laurea', 'Saratov State Agrarian University', 'Ingegneria',79, null, null, 'confermato'),
 ('GLFCDC88M29Y76KA', 'Candace', 'Gilfillan', '1988-08-29', 'CRESTVIEW', 'parziale', 'professore', 'laurea', 'Hyogo College of Medicine', 'Architettura',66, null, 'seconda', null),
 ('YRRLLO91A08OI18O', 'Ollie', 'Yirrell', '1991-01-08', 'RICHMOND', 'pieno', 'professore', 'dottorato di ricerca', 'Universite Amadou Hampaté Ba', 'Economia', null, 'Ollie Yirrell', 'prima', null),
 ('TLLGNT61D24P6XRK', 'Gweneth', 'Tillman', '1961-04-24', 'HASTINGS', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Tokyo Metropolitan Institute of Technology', 'Psicologia', null, 'Gweneth Tillman', null, 'confermato'),
 ('CCCBBN72R56BTY1Q', 'Bobina', 'Cicchillo', '1972-10-16', 'FORT WORTH', 'pieno', 'ricercatore', 'laurea', 'University of Information Technology and Management in Rzeszow', 'Filosofia',95, null, null, 'non confermato'),
 ('RCHBNR79T24QKRXQ', 'Abner', 'Richardes', '1979-12-24', 'NAPLES', 'pieno', 'ricercatore', 'laurea', 'Southwestern College Santa Fe', 'Scienze Politiche',69, null, null, 'confermato'),
 ('TMLLLN78E02X8YZV', 'Leoline', 'Tomala', '1978-05-02', 'MANCHESTER', 'pieno', 'professore', 'dottorato di ricerca', 'University of Louisiana at Lafayette', 'Informatica', null, 'Leoline Tomala', 'seconda', null),
 ('TRYZBE86T06KWXHP', 'Zeb', 'Trayhorn', '1986-12-06', 'BATON ROUGE', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Dallas Baptist University', 'Matematica', null, 'Zeb Trayhorn', null, 'non confermato'),
 ('SLDGGR88T03N8WTA', 'Gregor', 'Seldon', '1988-12-03', 'LOUISVILLE', 'parziale', 'professore', 'laurea', 'Ashkelon Academic College', 'Fisica',69, null, 'seconda', null),
 ('HLLRRN67A25VDTYS', 'Orran', 'Hulland', '1967-01-25', 'REDWOOD CITY', 'pieno', 'ricercatore', 'laurea', 'Universidad de las Américas - Puebla', 'Medicina',96, null, null, 'non confermato'),
 ('LCNSNT67R22313RV', 'Stanton', 'Le - Count', '1967-10-22', 'RICHLAND CENTER', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad del Sinú', 'Ingegneria', null, 'Stanton Le - Count', 'prima', null),
 ('RPRCSY74S25ADOGR', 'Cissy', 'Ropartz', '1974-11-25', 'DALLAS', 'pieno', 'ricercatore', 'dottorato di ricerca', 'Kobe Jogakuin University', 'Architettura', null, 'Cissy Ropartz', null, 'confermato'),
 ('PRSCRM91R27H9L8C', 'Charmian', 'Prisley', '1991-10-27', 'JEFFERSON CITY', 'parziale', 'professore', 'dottorato di ricerca', 'Université Rennes I', 'Economia', null, 'Charmian Prisley', 'seconda', null),
 ('MZZLEI64C51DMP3O', 'Leia', 'Mozzini', '1964-03-11', 'BOISE', 'pieno', 'ricercatore', 'laurea', 'Adeyemi College of Education', 'Psicologia',104, null, null, 'non confermato'),
 ('PLNSLN80H02Q230C', 'Suellen', 'Paolone', '1980-06-02', 'CHAPEL HILL', 'pieno', 'professore', 'dottorato di ricerca', 'Universidad San Francisco Xavier', 'Filosofia', null, 'Suellen Paolone', 'seconda', null),
 ('MNGSGN71A09U00IP', 'Sergent', 'Maingot', '1971-01-09', 'COLUMBUS', 'parziale', 'professore', 'laurea', 'Wilkes University', 'Scienze Politiche',92, null, 'seconda', null);
