INSERT INTO CORSO (ID, NOME, ORE, LAUREA) VALUES
  (1, 'Intelligenza Artificiale per la Salute', 72, 'magistrale'),
  (2, 'Strutture Dati per la Ricerca', 72, 'magistrale'),
  (3, 'Sistemi Operativi II', 56, 'magistrale'),
  (4, 'Algoritmi e Tecniche', 36, 'triennale'),
  (5, 'Algoritmi I', 72, 'magistrale'),
  (6, 'Programmazione e Laboratorio', 56, 'triennale'),
  (7, 'Machine Learning e Tecniche', 36, 'magistrale'),
  (8, 'Sicurezza Informatica Fondamentali', 56, 'magistrale'),
  (9, 'Basi di Dati per Professionisti', 72, 'magistrale'),
  (10, 'Programmazione per Professionisti', 56, 'triennale'),
  (11, 'Sicurezza Informatica per le Scienze Sociali', 36, 'triennale'),
  (12, 'Sicurezza Informatica Avanzati', 18, 'triennale'),
  (13, 'Algoritmi per l''Ingegneria', 36, 'triennale'),
  (14, 'Strutture Dati per Professionisti', 36, 'triennale'),
  (15, 'Sistemi Operativi per la Salute', 72, 'magistrale'),
  (16, 'Ingegneria del Software per le Scienze Sociali', 72, 'triennale'),
  (17, 'Algoritmi per la Salute', 72, 'triennale'),
  (18, 'Reti per la Salute', 56, 'triennale'),
  (19, 'Sicurezza Informatica e Sperimentazione', 72, 'triennale'),
  (20, 'Strutture Dati Base', 36, 'triennale'),
  (21, 'Sistemi Operativi e Tecniche', 56, 'magistrale'),
  (22, 'Reti per la Ricerca', 72, 'triennale'),
  (23, 'Intelligenza Artificiale per l''Ingegneria', 72, 'triennale'),
  (24, 'Sistemi Operativi I', 18, 'triennale'),
  (25, 'Strutture Dati per l''Ingegneria', 72, 'magistrale'),
  (26, 'Algoritmi Fondamentali', 18, 'triennale'),
  (27, 'Strutture Dati per le Scienze Sociali', 72, 'magistrale'),
  (28, 'Ingegneria del Software e Sperimentazione', 18, 'triennale'),
  (29, 'Sistemi Operativi e Laboratorio', 72, 'magistrale'),
  (30, 'Algoritmi Base', 56, 'triennale'),
  (31, 'Programmazione e Sperimentazione', 56, 'triennale'),
  (32, 'Programmazione per la Ricerca', 72, 'triennale'),
  (33, 'Reti Applicati', 36, 'magistrale'),
  (34, 'Sicurezza Informatica II', 72, 'triennale'),
  (35, 'Strutture Dati per la Salute', 56, 'triennale'),
  (36, 'Sistemi Operativi e Sperimentazione', 18, 'magistrale'),
  (37, 'Ingegneria del Software per la Ricerca', 72, 'magistrale'),
  (38, 'Basi di Dati per le Scienze Sociali', 36, 'magistrale'),
  (39, 'Sicurezza Informatica per l''Ingegneria', 72, 'triennale'),
  (40, 'Ingegneria del Software Fondamentali', 72, 'triennale'),
  (41, 'Ingegneria del Software I', 36, 'triennale'),
  (42, 'Strutture Dati I', 36, 'magistrale'),
  (43, 'Machine Learning II', 56, 'triennale'),
  (44, 'Strutture Dati Avanzati', 56, 'magistrale'),
  (45, 'Intelligenza Artificiale per la Ricerca', 56, 'triennale'),
  (46, 'Programmazione Base', 36, 'magistrale'),
  (47, 'Basi di Dati per la Salute', 72, 'triennale'),
  (48, 'Strutture Dati e Tecniche', 56, 'magistrale'),
  (49, 'Machine Learning per l''Ingegneria', 18, 'triennale'),
  (50, 'Ingegneria del Software per la Salute', 36, 'magistrale'),
  (51, 'Programmazione Applicati', 56, 'magistrale'),
  (52, 'Reti per le Scienze Sociali', 36, 'triennale'),
  (53, 'Programmazione per l''Ingegneria', 56, 'magistrale'),
  (54, 'Strutture Dati II', 56, 'triennale'),
  (55, 'Basi di Dati e Tecniche', 36, 'magistrale'),
  (56, 'Strutture Dati Applicati', 56, 'triennale'),
  (57, 'Ingegneria del Software per l''Ingegneria', 56, 'magistrale'),
  (58, 'Ingegneria del Software Applicati', 56, 'magistrale'),
  (59, 'Ingegneria del Software per Professionisti', 36, 'magistrale'),
  (60, 'Intelligenza Artificiale Applicati', 72, 'magistrale'),
  (61, 'Probabilità per Professionisti', 72, 'triennale'),
  (62, 'Matematica Computazionale per l''Ingegneria', 56, 'magistrale'),
  (63, 'Matematica Computazionale Base', 36, 'triennale'),
  (64, 'Equazioni Differenziali Avanzati', 72, 'triennale'),
  (65, 'Topologia per la Ricerca', 56, 'triennale'),
  (66, 'Logica Fondamentali', 72, 'triennale'),
  (67, 'Probabilità e Laboratorio', 56, 'triennale'),
  (68, 'Logica per la Ricerca', 72, 'triennale'),
  (69, 'Topologia e Tecniche', 72, 'magistrale'),
  (70, 'Equazioni Differenziali per la Salute', 72, 'triennale'),
  (71, 'Matematica Computazionale per Professionisti', 18, 'triennale'),
  (72, 'Statistica Fondamentali', 56, 'triennale'),
  (73, 'Matematica Finanziaria Avanzati', 72, 'magistrale'),
  (74, 'Logica Base', 18, 'triennale'),
  (75, 'Equazioni Differenziali per Professionisti', 36, 'magistrale'),
  (76, 'Matematica Finanziaria per Professionisti', 36, 'magistrale'),
  (77, 'Analisi Matematica per le Scienze Sociali', 18, 'magistrale'),
  (78, 'Geometria e Sperimentazione', 36, 'magistrale'),
  (79, 'Probabilità II', 72, 'triennale'),
  (80, 'Equazioni Differenziali per le Scienze Sociali', 56, 'magistrale'),
  (81, 'Geometria per le Scienze Sociali', 72, 'magistrale'),
  (82, 'Geometria I', 18, 'triennale'),
  (83, 'Analisi Matematica e Sperimentazione', 56, 'triennale'),
  (84, 'Algebra per Professionisti', 36, 'triennale'),
  (85, 'Equazioni Differenziali Applicati', 56, 'magistrale'),
  (86, 'Topologia e Laboratorio', 72, 'triennale'),
  (87, 'Algebra Fondamentali', 72, 'magistrale'),
  (88, 'Analisi Matematica per Professionisti', 36, 'magistrale'),
  (89, 'Matematica Finanziaria per l''Ingegneria', 72, 'triennale'),
  (90, 'Statistica e Laboratorio', 56, 'triennale'),
  (91, 'Matematica Finanziaria Base', 36, 'magistrale'),
  (92, 'Matematica Computazionale e Laboratorio', 72, 'triennale'),
  (93, 'Probabilità Fondamentali', 72, 'magistrale'),
  (94, 'Matematica Computazionale II', 72, 'triennale'),
  (95, 'Probabilità e Tecniche', 18, 'triennale'),
  (96, 'Statistica I', 18, 'triennale'),
  (97, 'Algebra per la Salute', 72, 'magistrale'),
  (98, 'Matematica Finanziaria Applicati', 72, 'magistrale'),
  (99, 'Algebra per le Scienze Sociali', 36, 'triennale'),
  (100, 'Topologia I', 36, 'triennale'),
  (101, 'Matematica Computazionale e Sperimentazione', 72, 'triennale'),
  (102, 'Matematica Computazionale Avanzati', 72, 'triennale'),
  (103, 'Statistica e Sperimentazione', 72, 'magistrale'),
  (104, 'Topologia per l''Ingegneria', 72, 'magistrale'),
  (105, 'Algebra Base', 18, 'triennale'),
  (106, 'Probabilità Avanzati', 56, 'triennale'),
  (107, 'Equazioni Differenziali I', 36, 'magistrale'),
  (108, 'Topologia per la Salute', 18, 'triennale'),
  (109, 'Probabilità per la Ricerca', 56, 'triennale'),
  (110, 'Statistica per l''Ingegneria', 18, 'triennale'),
  (111, 'Probabilità e Sperimentazione', 18, 'magistrale'),
  (112, 'Geometria per la Ricerca', 36, 'triennale'),
  (113, 'Matematica Finanziaria Fondamentali', 72, 'triennale'),
  (114, 'Statistica per la Ricerca', 18, 'magistrale'),
  (115, 'Matematica Finanziaria per la Salute', 36, 'magistrale'),
  (116, 'Probabilità I', 56, 'triennale'),
  (117, 'Algebra per la Ricerca', 72, 'triennale'),
  (118, 'Algebra e Laboratorio', 36, 'magistrale'),
  (119, 'Logica per le Scienze Sociali', 36, 'magistrale'),
  (120, 'Logica per l''Ingegneria', 72, 'triennale'),
  (121, 'Termodinamica per l''Ingegneria', 56, 'magistrale'),
  (122, 'Fisica delle Particelle per le Scienze Sociali', 56, 'triennale'),
  (123, 'Termodinamica per Professionisti', 72, 'magistrale'),
  (124, 'Termodinamica per la Ricerca', 72, 'triennale'),
  (125, 'Ottica e Sperimentazione', 36, 'magistrale'),
  (126, 'Relatività II', 56, 'magistrale'),
  (127, 'Fisica Teorica e Tecniche', 36, 'magistrale'),
  (128, 'Fisica Nucleare Fondamentali', 18, 'triennale'),
  (129, 'Termodinamica Fondamentali', 72, 'triennale'),
  (130, 'Termodinamica e Sperimentazione', 36, 'magistrale'),
  (131, 'Fisica delle Particelle Avanzati', 72, 'triennale'),
  (132, 'Elettromagnetismo Fondamentali', 56, 'triennale'),
  (133, 'Relatività Base', 56, 'magistrale'),
  (134, 'Termodinamica II', 36, 'triennale'),
  (135, 'Ottica Fondamentali', 56, 'triennale'),
  (136, 'Termodinamica Avanzati', 36, 'magistrale'),
  (137, 'Termodinamica Applicati', 36, 'magistrale'),
  (138, 'Meccanica Avanzati', 56, 'triennale'),
  (139, 'Ottica per Professionisti', 36, 'magistrale'),
  (140, 'Termodinamica e Laboratorio', 72, 'triennale'),
  (141, 'Termodinamica Base', 56, 'magistrale'),
  (142, 'Relatività Applicati', 72, 'triennale'),
  (143, 'Elettromagnetismo Base', 18, 'triennale'),
  (144, 'Fisica delle Particelle II', 36, 'triennale'),
  (145, 'Ottica e Tecniche', 72, 'triennale'),
  (146, 'Elettromagnetismo per la Ricerca', 18, 'magistrale'),
  (147, 'Fisica Nucleare per l''Ingegneria', 56, 'triennale'),
  (148, 'Fisica Quantistica I', 18, 'triennale'),
  (149, 'Fisica Computazionale per Professionisti', 56, 'triennale'),
  (150, 'Relatività e Laboratorio', 36, 'magistrale'),
  (151, 'Relatività Fondamentali', 18, 'triennale'),
  (152, 'Fisica delle Particelle per l''Ingegneria', 18, 'triennale'),
  (153, 'Fisica delle Particelle Fondamentali', 18, 'triennale'),
  (154, 'Fisica Nucleare II', 36, 'magistrale'),
  (155, 'Fisica Computazionale per l''Ingegneria', 56, 'triennale'),
  (156, 'Fisica delle Particelle per la Ricerca', 18, 'triennale'),
  (157, 'Fisica Computazionale Base', 18, 'magistrale'),
  (158, 'Fisica Quantistica Avanzati', 18, 'magistrale'),
  (159, 'Fisica Teorica I', 72, 'magistrale'),
  (160, 'Ottica Base', 36, 'magistrale'),
  (161, 'Termodinamica I', 18, 'triennale'),
  (162, 'Elettromagnetismo per la Salute', 56, 'magistrale'),
  (163, 'Fisica Computazionale Fondamentali', 18, 'magistrale'),
  (164, 'Fisica Quantistica Base', 72, 'triennale'),
  (165, 'Fisica delle Particelle e Tecniche', 18, 'magistrale'),
  (166, 'Meccanica per Professionisti', 36, 'triennale'),
  (167, 'Elettromagnetismo per le Scienze Sociali', 56, 'magistrale'),
  (168, 'Elettromagnetismo II', 36, 'magistrale'),
  (169, 'Meccanica II', 72, 'magistrale'),
  (170, 'Fisica Teorica Base', 56, 'triennale'),
  (171, 'Fisica Teorica II', 18, 'magistrale'),
  (172, 'Fisica Computazionale Applicati', 56, 'triennale'),
  (173, 'Relatività per la Ricerca', 18, 'triennale'),
  (174, 'Fisica Quantistica per Professionisti', 18, 'triennale'),
  (175, 'Meccanica e Laboratorio', 18, 'magistrale'),
  (176, 'Elettromagnetismo Applicati', 18, 'magistrale'),
  (177, 'Fisica Quantistica II', 36, 'magistrale'),
  (178, 'Fisica Nucleare I', 18, 'magistrale'),
  (179, 'Termodinamica per la Salute', 18, 'triennale'),
  (180, 'Fisica Quantistica per la Ricerca', 18, 'magistrale'),
  (181, 'Fisiologia per le Scienze Sociali', 56, 'magistrale'),
  (182, 'Chirurgia Base', 72, 'triennale'),
  (183, 'Chirurgia e Laboratorio', 56, 'magistrale'),
  (184, 'Psichiatria e Laboratorio', 72, 'magistrale'),
  (185, 'Psichiatria per le Scienze Sociali', 36, 'triennale'),
  (186, 'Patologia Avanzati', 72, 'triennale'),
  (187, 'Farmacologia per la Salute', 56, 'triennale'),
  (188, 'Chirurgia Avanzati', 72, 'magistrale'),
  (189, 'Fisiologia e Laboratorio', 36, 'magistrale'),
  (190, 'Neurologia Avanzati', 36, 'magistrale'),
  (191, 'Fisiologia Avanzati', 36, 'magistrale'),
  (192, 'Chirurgia per le Scienze Sociali', 18, 'triennale'),
  (193, 'Pediatria Applicati', 72, 'triennale'),
  (194, 'Psichiatria e Tecniche', 18, 'magistrale'),
  (195, 'Patologia e Laboratorio', 56, 'magistrale'),
  (196, 'Chirurgia per la Ricerca', 72, 'magistrale'),
  (197, 'Microbiologia e Laboratorio', 18, 'triennale'),
  (198, 'Patologia per la Ricerca', 18, 'triennale'),
  (199, 'Fisiologia Applicati', 72, 'magistrale'),
  (200, 'Chirurgia per l''Ingegneria', 18, 'magistrale'),
  (201, 'Farmacologia per le Scienze Sociali', 56, 'magistrale'),
  (202, 'Microbiologia e Sperimentazione', 18, 'triennale'),
  (203, 'Psichiatria Avanzati', 36, 'magistrale'),
  (204, 'Patologia Base', 36, 'magistrale'),
  (205, 'Medicina Interna per la Salute', 18, 'magistrale'),
  (206, 'Medicina Interna e Sperimentazione', 72, 'triennale'),
  (207, 'Fisiologia per la Ricerca', 36, 'triennale'),
  (208, 'Anatomia Avanzati', 36, 'triennale'),
  (209, 'Farmacologia e Sperimentazione', 72, 'magistrale'),
  (210, 'Fisiologia e Tecniche', 56, 'triennale'),
  (211, 'Anatomia Base', 36, 'magistrale'),
  (212, 'Anatomia per le Scienze Sociali', 18, 'triennale'),
  (213, 'Psichiatria per l''Ingegneria', 72, 'magistrale'),
  (214, 'Anatomia per l''Ingegneria', 72, 'triennale'),
  (215, 'Patologia I', 56, 'magistrale'),
  (216, 'Microbiologia per le Scienze Sociali', 72, 'magistrale'),
  (217, 'Microbiologia per l''Ingegneria', 36, 'magistrale'),
  (218, 'Farmacologia Fondamentali', 36, 'triennale'),
  (219, 'Medicina Interna per la Ricerca', 56, 'magistrale'),
  (220, 'Pediatria per la Ricerca', 72, 'magistrale'),
  (221, 'Psichiatria per la Salute', 56, 'magistrale'),
  (222, 'Microbiologia Applicati', 18, 'magistrale'),
  (223, 'Anatomia per la Ricerca', 56, 'triennale'),
  (224, 'Neurologia per la Salute', 56, 'triennale'),
  (225, 'Farmacologia I', 18, 'triennale'),
  (226, 'Psichiatria e Sperimentazione', 72, 'magistrale'),
  (227, 'Patologia Applicati', 36, 'magistrale'),
  (228, 'Chirurgia e Tecniche', 18, 'magistrale'),
  (229, 'Patologia e Tecniche', 36, 'magistrale'),
  (230, 'Pediatria I', 36, 'magistrale'),
  (231, 'Anatomia e Laboratorio', 36, 'triennale'),
  (232, 'Pediatria per le Scienze Sociali', 18, 'magistrale'),
  (233, 'Patologia II', 36, 'magistrale'),
  (234, 'Fisiologia e Sperimentazione', 56, 'triennale'),
  (235, 'Chirurgia per Professionisti', 72, 'triennale'),
  (236, 'Chirurgia I', 56, 'triennale'),
  (237, 'Patologia per Professionisti', 72, 'magistrale'),
  (238, 'Chirurgia Applicati', 56, 'triennale'),
  (239, 'Patologia per l''Ingegneria', 56, 'magistrale'),
  (240, 'Anatomia per Professionisti', 72, 'triennale'),
  (241, 'Tecnologia dei Materiali e Tecniche', 56, 'triennale'),
  (242, 'Robotica Base', 72, 'triennale'),
  (243, 'Disegno Tecnico per Professionisti', 18, 'triennale'),
  (244, 'Disegno Tecnico II', 36, 'triennale'),
  (245, 'Disegno Tecnico per le Scienze Sociali', 18, 'magistrale'),
  (246, 'Elettrotecnica e Laboratorio', 18, 'magistrale'),
  (247, 'Automazione per la Ricerca', 18, 'triennale'),
  (248, 'Fisica Tecnica per l''Ingegneria', 72, 'magistrale'),
  (249, 'Tecnologia dei Materiali per l''Ingegneria', 72, 'magistrale'),
  (250, 'Disegno Tecnico per la Salute', 72, 'triennale'),
  (251, 'Costruzioni per la Ricerca', 36, 'triennale'),
  (252, 'Costruzioni Base', 18, 'magistrale'),
  (253, 'Fisica Tecnica II', 56, 'triennale'),
  (254, 'Scienza delle Costruzioni II', 36, 'magistrale'),
  (255, 'Tecnologia dei Materiali per Professionisti', 18, 'triennale'),
  (256, 'Disegno Tecnico e Tecniche', 72, 'triennale'),
  (257, 'Ingegneria Elettronica Fondamentali', 36, 'magistrale'),
  (258, 'Tecnologia dei Materiali Avanzati', 18, 'magistrale'),
  (259, 'Ingegneria Elettronica per Professionisti', 56, 'magistrale'),
  (260, 'Automazione e Laboratorio', 18, 'triennale'),
  (261, 'Ingegneria Elettronica e Tecniche', 72, 'triennale'),
  (262, 'Scienza delle Costruzioni I', 72, 'triennale'),
  (263, 'Scienza delle Costruzioni Avanzati', 36, 'triennale'),
  (264, 'Automazione Base', 72, 'triennale'),
  (265, 'Ingegneria Elettronica per le Scienze Sociali', 72, 'magistrale'),
  (266, 'Scienza delle Costruzioni Fondamentali', 72, 'triennale'),
  (267, 'Disegno Tecnico per l''Ingegneria', 56, 'triennale'),
  (268, 'Costruzioni Avanzati', 56, 'magistrale'),
  (269, 'Costruzioni I', 36, 'magistrale'),
  (270, 'Robotica Avanzati', 36, 'triennale'),
  (271, 'Disegno Tecnico per la Ricerca', 72, 'triennale'),
  (272, 'Energetica Avanzati', 72, 'magistrale'),
  (273, 'Energetica Fondamentali', 72, 'triennale'),
  (274, 'Scienza delle Costruzioni per l''Ingegneria', 18, 'triennale'),
  (275, 'Scienza delle Costruzioni per la Ricerca', 72, 'triennale'),
  (276, 'Tecnologia dei Materiali e Laboratorio', 36, 'triennale'),
  (277, 'Ingegneria Elettronica e Laboratorio', 36, 'magistrale'),
  (278, 'Scienza delle Costruzioni Base', 72, 'magistrale'),
  (279, 'Energetica II', 56, 'magistrale'),
  (280, 'Fisica Tecnica per la Ricerca', 72, 'triennale'),
  (281, 'Ingegneria Elettronica Applicati', 36, 'triennale'),
  (282, 'Scienza delle Costruzioni e Tecniche', 18, 'magistrale'),
  (283, 'Ingegneria Elettronica I', 72, 'magistrale'),
  (284, 'Robotica e Tecniche', 72, 'triennale'),
  (285, 'Tecnologia dei Materiali I', 72, 'triennale'),
  (286, 'Ingegneria Elettronica Avanzati', 72, 'magistrale'),
  (287, 'Elettrotecnica Avanzati', 72, 'magistrale'),
  (288, 'Disegno Tecnico Avanzati', 56, 'magistrale'),
  (289, 'Automazione I', 72, 'triennale'),
  (290, 'Elettrotecnica Applicati', 56, 'magistrale'),
  (291, 'Disegno Tecnico I', 72, 'triennale'),
  (292, 'Elettrotecnica per le Scienze Sociali', 36, 'magistrale'),
  (293, 'Energetica e Sperimentazione', 56, 'triennale'),
  (294, 'Energetica per la Ricerca', 36, 'triennale'),
  (295, 'Automazione per Professionisti', 72, 'triennale'),
  (296, 'Energetica e Tecniche', 18, 'triennale'),
  (297, 'Elettrotecnica e Sperimentazione', 36, 'triennale'),
  (298, 'Elettrotecnica I', 56, 'magistrale'),
  (299, 'Energetica per l''Ingegneria', 18, 'triennale'),
  (300, 'Elettrotecnica II', 72, 'magistrale'),
  (301, 'Tecnologie Costruttive e Sperimentazione', 72, 'magistrale'),
  (302, 'Architettura del Paesaggio Applicati', 56, 'triennale'),
  (303, 'Urbanistica Avanzati', 72, 'triennale'),
  (304, 'Energia e Ambiente per la Ricerca', 36, 'triennale'),
  (305, 'Restauro Fondamentali', 36, 'magistrale'),
  (306, 'Disegno per la Salute', 18, 'triennale'),
  (307, 'Materiali da Costruzione Applicati', 36, 'triennale'),
  (308, 'Restauro I', 56, 'magistrale'),
  (309, 'Disegno per l''Ingegneria', 56, 'magistrale'),
  (310, 'Urbanistica e Laboratorio', 72, 'magistrale'),
  (311, 'Strutture e Sperimentazione', 72, 'triennale'),
  (312, 'Storia dell''Architettura per la Salute', 56, 'magistrale'),
  (313, 'Urbanistica Fondamentali', 18, 'magistrale'),
  (314, 'Progettazione Architettonica II', 56, 'magistrale'),
  (315, 'Urbanistica I', 56, 'triennale'),
  (316, 'Tecnologie Costruttive per la Salute', 36, 'triennale'),
  (317, 'Energia e Ambiente per l''Ingegneria', 56, 'triennale'),
  (318, 'Storia dell''Architettura Fondamentali', 72, 'magistrale'),
  (319, 'Urbanistica per l''Ingegneria', 72, 'magistrale'),
  (320, 'Storia dell''Architettura e Tecniche', 36, 'magistrale'),
  (321, 'Strutture Fondamentali', 72, 'magistrale'),
  (322, 'Strutture I', 36, 'triennale'),
  (323, 'Urbanistica Base', 72, 'triennale'),
  (324, 'Urbanistica per Professionisti', 36, 'magistrale'),
  (325, 'Progettazione Architettonica e Laboratorio', 56, 'triennale'),
  (326, 'Architettura del Paesaggio II', 56, 'magistrale'),
  (327, 'Materiali da Costruzione e Sperimentazione', 18, 'magistrale'),
  (328, 'Storia dell''Architettura e Sperimentazione', 18, 'magistrale'),
  (329, 'Restauro per la Salute', 18, 'magistrale'),
  (330, 'Disegno Avanzati', 36, 'triennale'),
  (331, 'Restauro II', 72, 'magistrale'),
  (332, 'Tecnologie Costruttive II', 36, 'triennale'),
  (333, 'Materiali da Costruzione II', 36, 'magistrale'),
  (334, 'Storia dell''Architettura Avanzati', 72, 'magistrale'),
  (335, 'Restauro per la Ricerca', 36, 'triennale'),
  (336, 'Materiali da Costruzione per la Ricerca', 18, 'triennale'),
  (337, 'Disegno per le Scienze Sociali', 72, 'triennale'),
  (338, 'Restauro per Professionisti', 56, 'triennale'),
  (339, 'Architettura del Paesaggio per la Ricerca', 36, 'triennale'),
  (340, 'Restauro e Laboratorio', 56, 'magistrale'),
  (341, 'Tecnologie Costruttive Base', 72, 'magistrale'),
  (342, 'Storia dell''Architettura I', 56, 'magistrale'),
  (343, 'Strutture e Tecniche', 56, 'magistrale'),
  (344, 'Restauro Applicati', 72, 'triennale'),
  (345, 'Tecnologie Costruttive e Laboratorio', 18, 'triennale'),
  (346, 'Storia dell''Architettura per l''Ingegneria', 56, 'triennale'),
  (347, 'Energia e Ambiente Avanzati', 18, 'triennale'),
  (348, 'Storia dell''Architettura per Professionisti', 18, 'magistrale'),
  (349, 'Materiali da Costruzione per l''Ingegneria', 18, 'magistrale'),
  (350, 'Materiali da Costruzione per Professionisti', 36, 'triennale'),
  (351, 'Disegno Fondamentali', 18, 'magistrale'),
  (352, 'Energia e Ambiente e Tecniche', 36, 'magistrale'),
  (353, 'Progettazione Architettonica per la Salute', 18, 'magistrale'),
  (354, 'Progettazione Architettonica per la Ricerca', 18, 'magistrale'),
  (355, 'Restauro e Tecniche', 36, 'magistrale'),
  (356, 'Strutture e Laboratorio', 56, 'magistrale'),
  (357, 'Urbanistica Applicati', 18, 'magistrale'),
  (358, 'Restauro Avanzati', 18, 'triennale'),
  (359, 'Progettazione Architettonica e Sperimentazione', 72, 'triennale'),
  (360, 'Strutture Base', 18, 'magistrale'),
  (361, 'Finanza Aziendale per le Scienze Sociali', 56, 'magistrale'),
  (362, 'Commercio Internazionale Avanzati', 18, 'triennale'),
  (363, 'Microeconomia e Sperimentazione', 56, 'magistrale'),
  (364, 'Economia Politica per l''Ingegneria', 18, 'triennale'),
  (365, 'Microeconomia Avanzati', 36, 'triennale'),
  (366, 'Economia Politica II', 72, 'magistrale'),
  (367, 'Macroeconomia II', 56, 'triennale'),
  (368, 'Macroeconomia per l''Ingegneria', 72, 'magistrale'),
  (369, 'Marketing e Sperimentazione', 72, 'magistrale'),
  (370, 'Statistica Economica Fondamentali', 36, 'triennale'),
  (371, 'Contabilità per Professionisti', 18, 'triennale'),
  (372, 'Politica Economica per le Scienze Sociali', 72, 'triennale'),
  (373, 'Politica Economica per l''Ingegneria', 56, 'triennale'),
  (374, 'Contabilità per le Scienze Sociali', 72, 'triennale'),
  (375, 'Statistica Economica per le Scienze Sociali', 18, 'triennale'),
  (376, 'Marketing Fondamentali', 56, 'triennale'),
  (377, 'Economia dello Sviluppo per la Ricerca', 36, 'magistrale'),
  (378, 'Economia dello Sviluppo per la Salute', 18, 'magistrale'),
  (379, 'Economia Politica Fondamentali', 72, 'triennale'),
  (380, 'Economia dello Sviluppo e Tecniche', 18, 'triennale'),
  (381, 'Contabilità per la Salute', 72, 'magistrale'),
  (382, 'Contabilità Base', 72, 'magistrale'),
  (383, 'Finanza Aziendale II', 56, 'triennale'),
  (384, 'Economia dello Sviluppo e Laboratorio', 72, 'magistrale'),
  (385, 'Finanza Aziendale Base', 72, 'magistrale'),
  (386, 'Macroeconomia e Sperimentazione', 72, 'magistrale'),
  (387, 'Economia Politica Base', 72, 'triennale'),
  (388, 'Statistica Economica Avanzati', 18, 'triennale'),
  (389, 'Politica Economica e Tecniche', 56, 'triennale'),
  (390, 'Commercio Internazionale II', 56, 'triennale'),
  (391, 'Finanza Aziendale e Sperimentazione', 72, 'magistrale'),
  (392, 'Commercio Internazionale per Professionisti', 56, 'magistrale'),
  (393, 'Macroeconomia Base', 36, 'triennale'),
  (394, 'Marketing per la Salute', 56, 'triennale'),
  (395, 'Microeconomia Applicati', 72, 'triennale'),
  (396, 'Statistica Economica Base', 56, 'triennale'),
  (397, 'Statistica Economica e Laboratorio', 72, 'triennale'),
  (398, 'Politica Economica Base', 72, 'magistrale'),
  (399, 'Politica Economica per la Salute', 36, 'magistrale'),
  (400, 'Microeconomia per la Salute', 18, 'magistrale'),
  (401, 'Politica Economica Applicati', 36, 'triennale'),
  (402, 'Economia Politica per la Salute', 72, 'magistrale'),
  (403, 'Politica Economica per Professionisti', 36, 'magistrale'),
  (404, 'Statistica Economica II', 56, 'magistrale'),
  (405, 'Contabilità Applicati', 72, 'magistrale'),
  (406, 'Economia dello Sviluppo e Sperimentazione', 56, 'triennale'),
  (407, 'Finanza Aziendale e Laboratorio', 56, 'magistrale'),
  (408, 'Economia dello Sviluppo per Professionisti', 56, 'triennale'),
  (409, 'Commercio Internazionale e Tecniche', 72, 'magistrale'),
  (410, 'Statistica Economica per la Ricerca', 18, 'triennale'),
  (411, 'Microeconomia per l''Ingegneria', 36, 'triennale'),
  (412, 'Microeconomia e Laboratorio', 56, 'triennale'),
  (413, 'Marketing Applicati', 18, 'magistrale'),
  (414, 'Finanza Aziendale per la Ricerca', 18, 'magistrale'),
  (415, 'Commercio Internazionale Base', 36, 'magistrale'),
  (416, 'Finanza Aziendale per la Salute', 56, 'triennale'),
  (417, 'Statistica Economica per l''Ingegneria', 72, 'magistrale'),
  (418, 'Economia dello Sviluppo Avanzati', 18, 'magistrale'),
  (419, 'Finanza Aziendale e Tecniche', 72, 'triennale'),
  (420, 'Economia Politica per la Ricerca', 36, 'triennale'),
  (421, 'Neuropsicologia per le Scienze Sociali', 36, 'triennale'),
  (422, 'Psicologia Clinica Applicati', 18, 'magistrale'),
  (423, 'Psicologia Generale per l''Ingegneria', 56, 'magistrale'),
  (424, 'Psicologia Cognitiva e Sperimentazione', 56, 'triennale'),
  (425, 'Psicometria per le Scienze Sociali', 36, 'triennale'),
  (426, 'Psicologia Clinica II', 18, 'magistrale'),
  (427, 'Teorie della Personalità per la Ricerca', 56, 'triennale'),
  (428, 'Psicometria per la Salute', 36, 'triennale'),
  (429, 'Psicologia del Lavoro Base', 36, 'magistrale'),
  (430, 'Psicologia del Lavoro per la Salute', 72, 'triennale'),
  (431, 'Psicometria e Laboratorio', 36, 'magistrale'),
  (432, 'Psicometria II', 56, 'triennale'),
  (433, 'Psicologia Cognitiva per la Salute', 72, 'triennale'),
  (434, 'Psicologia dello Sviluppo Fondamentali', 56, 'magistrale'),
  (435, 'Psicopatologia Fondamentali', 36, 'triennale'),
  (436, 'Psicometria per l''Ingegneria', 18, 'magistrale'),
  (437, 'Neuropsicologia per la Salute', 56, 'triennale'),
  (438, 'Psicologia del Lavoro e Sperimentazione', 56, 'magistrale'),
  (439, 'Teorie della Personalità Avanzati', 56, 'triennale'),
  (440, 'Psicologia dello Sviluppo Base', 36, 'triennale'),
  (441, 'Psicologia dello Sviluppo e Laboratorio', 36, 'magistrale'),
  (442, 'Psicologia Sociale Fondamentali', 18, 'triennale'),
  (443, 'Psicologia Generale per le Scienze Sociali', 56, 'triennale'),
  (444, 'Psicologia Generale Applicati', 56, 'triennale'),
  (445, 'Psicopatologia I', 72, 'magistrale'),
  (446, 'Teorie della Personalità Fondamentali', 72, 'magistrale'),
  (447, 'Psicometria Avanzati', 72, 'triennale'),
  (448, 'Psicologia del Lavoro Avanzati', 18, 'triennale'),
  (449, 'Psicologia dello Sviluppo II', 18, 'magistrale'),
  (450, 'Neuropsicologia e Tecniche', 18, 'magistrale'),
  (451, 'Teorie della Personalità per l''Ingegneria', 72, 'triennale'),
  (452, 'Teorie della Personalità Applicati', 36, 'triennale'),
  (453, 'Psicologia Sociale per la Ricerca', 56, 'triennale'),
  (454, 'Neuropsicologia Fondamentali', 56, 'triennale'),
  (455, 'Psicologia del Lavoro Applicati', 18, 'triennale'),
  (456, 'Psicologia Generale e Tecniche', 72, 'triennale'),
  (457, 'Neuropsicologia e Laboratorio', 56, 'triennale'),
  (458, 'Psicopatologia e Tecniche', 56, 'triennale'),
  (459, 'Psicologia dello Sviluppo Applicati', 18, 'magistrale'),
  (460, 'Psicologia dello Sviluppo I', 18, 'triennale'),
  (461, 'Psicologia Cognitiva per le Scienze Sociali', 56, 'magistrale'),
  (462, 'Psicologia Clinica Fondamentali', 36, 'triennale'),
  (463, 'Teorie della Personalità II', 56, 'triennale'),
  (464, 'Psicologia Cognitiva e Tecniche', 56, 'magistrale'),
  (465, 'Psicologia Sociale Applicati', 18, 'magistrale'),
  (466, 'Psicopatologia per la Ricerca', 36, 'magistrale'),
  (467, 'Neuropsicologia e Sperimentazione', 56, 'triennale'),
  (468, 'Teorie della Personalità per le Scienze Sociali', 56, 'magistrale'),
  (469, 'Teorie della Personalità per la Salute', 18, 'triennale'),
  (470, 'Psicologia Cognitiva Base', 56, 'triennale'),
  (471, 'Psicologia del Lavoro e Laboratorio', 56, 'triennale'),
  (472, 'Psicologia dello Sviluppo Avanzati', 18, 'magistrale'),
  (473, 'Psicologia Cognitiva e Laboratorio', 18, 'magistrale'),
  (474, 'Psicologia Sociale e Laboratorio', 56, 'triennale'),
  (475, 'Psicologia Sociale II', 18, 'triennale'),
  (476, 'Psicologia Cognitiva Fondamentali', 36, 'triennale'),
  (477, 'Psicologia Clinica e Tecniche', 36, 'magistrale'),
  (478, 'Teorie della Personalità e Laboratorio', 18, 'magistrale'),
  (479, 'Psicologia Generale Fondamentali', 36, 'magistrale'),
  (480, 'Psicologia Sociale per le Scienze Sociali', 72, 'triennale'),
  (481, 'Etica Fondamentali', 56, 'triennale'),
  (482, 'Filosofia della Scienza Fondamentali', 56, 'magistrale'),
  (483, 'Filosofia Politica per la Salute', 36, 'magistrale'),
  (484, 'Filosofia Contemporanea II', 18, 'magistrale'),
  (485, 'Filosofia Contemporanea e Laboratorio', 72, 'magistrale'),
  (486, 'Filosofia Moderna per le Scienze Sociali', 72, 'triennale'),
  (487, 'Filosofia della Scienza Applicati', 72, 'triennale'),
  (488, 'Estetica Base', 56, 'triennale'),
  (489, 'Metafisica Applicati', 36, 'magistrale'),
  (490, 'Filosofia Politica per Professionisti', 18, 'triennale'),
  (491, 'Filosofia Contemporanea per la Ricerca', 56, 'triennale'),
  (492, 'Epistemologia Fondamentali', 72, 'magistrale'),
  (493, 'Estetica e Tecniche', 36, 'magistrale'),
  (494, 'Etica e Laboratorio', 18, 'triennale'),
  (495, 'Filosofia Politica e Tecniche', 36, 'triennale'),
  (496, 'Filosofia della Scienza Avanzati', 36, 'triennale'),
  (497, 'Metafisica I', 36, 'magistrale'),
  (498, 'Etica per Professionisti', 56, 'triennale'),
  (499, 'Estetica per le Scienze Sociali', 72, 'magistrale'),
  (500, 'Metafisica e Laboratorio', 72, 'triennale'),
  (501, 'Filosofia Politica e Sperimentazione', 36, 'magistrale'),
  (502, 'Metafisica per Professionisti', 56, 'magistrale'),
  (503, 'Logica e Laboratorio', 72, 'magistrale'),
  (504, 'Metafisica Base', 18, 'triennale'),
  (505, 'Filosofia della Scienza e Sperimentazione', 72, 'triennale'),
  (506, 'Filosofia Politica Base', 36, 'magistrale'),
  (507, 'Etica per la Ricerca', 18, 'triennale'),
  (508, 'Metafisica e Tecniche', 18, 'magistrale'),
  (509, 'Filosofia della Scienza per l''Ingegneria', 56, 'triennale'),
  (510, 'Estetica per la Ricerca', 72, 'magistrale'),
  (511, 'Filosofia Moderna e Tecniche', 18, 'magistrale'),
  (512, 'Epistemologia per la Ricerca', 36, 'triennale'),
  (513, 'Filosofia Antica e Tecniche', 72, 'magistrale'),
  (514, 'Estetica Avanzati', 18, 'triennale'),
  (515, 'Filosofia Contemporanea Fondamentali', 36, 'magistrale'),
  (516, 'Logica Applicati', 72, 'magistrale'),
  (517, 'Filosofia Antica e Sperimentazione', 72, 'magistrale'),
  (518, 'Filosofia Politica I', 72, 'triennale'),
  (519, 'Filosofia Contemporanea per la Salute', 72, 'triennale'),
  (520, 'Filosofia Moderna per la Salute', 72, 'magistrale'),
  (521, 'Filosofia Moderna per la Ricerca', 72, 'triennale'),
  (522, 'Logica per Professionisti', 36, 'magistrale'),
  (523, 'Estetica per la Salute', 72, 'magistrale'),
  (524, 'Filosofia della Scienza e Tecniche', 18, 'triennale'),
  (525, 'Logica e Sperimentazione', 36, 'magistrale'),
  (526, 'Filosofia Politica per l''Ingegneria', 18, 'triennale'),
  (527, 'Filosofia Antica e Laboratorio', 56, 'triennale'),
  (528, 'Filosofia Politica Avanzati', 72, 'magistrale'),
  (529, 'Filosofia Politica Fondamentali', 56, 'triennale'),
  (530, 'Metafisica Fondamentali', 72, 'magistrale'),
  (531, 'Filosofia della Scienza I', 36, 'triennale'),
  (532, 'Filosofia della Scienza per Professionisti', 36, 'triennale'),
  (533, 'Etica II', 36, 'triennale'),
  (534, 'Filosofia Antica per la Ricerca', 72, 'magistrale'),
  (535, 'Filosofia Contemporanea per l''Ingegneria', 36, 'triennale'),
  (536, 'Logica Base', 56, 'magistrale'),
  (537, 'Filosofia Moderna e Sperimentazione', 56, 'triennale'),
  (538, 'Filosofia Politica e Laboratorio', 72, 'magistrale'),
  (539, 'Filosofia Antica Applicati', 72, 'triennale'),
  (540, 'Filosofia della Scienza Base', 56, 'magistrale'),
  (541, 'Scienza Politica per la Ricerca', 56, 'magistrale'),
  (542, 'Economia Pubblica per l''Ingegneria', 72, 'triennale'),
  (543, 'Politiche Pubbliche per la Ricerca', 72, 'magistrale'),
  (544, 'Geopolitica e Sperimentazione', 18, 'magistrale'),
  (545, 'Scienza Politica I', 18, 'magistrale'),
  (546, 'Sociologia Fondamentali', 36, 'magistrale'),
  (547, 'Teoria Politica II', 18, 'magistrale'),
  (548, 'Sociologia I', 18, 'magistrale'),
  (549, 'Politiche Pubbliche Base', 36, 'magistrale'),
  (550, 'Politiche Pubbliche II', 36, 'magistrale'),
  (551, 'Relazioni Internazionali per Professionisti', 36, 'magistrale'),
  (552, 'Sociologia e Laboratorio', 36, 'magistrale'),
  (553, 'Sociologia e Sperimentazione', 36, 'magistrale'),
  (554, 'Relazioni Internazionali per la Ricerca', 18, 'triennale'),
  (555, 'Scienza Politica Fondamentali', 72, 'triennale'),
  (556, 'Comunicazione Politica Avanzati', 72, 'magistrale'),
  (557, 'Geopolitica II', 72, 'magistrale'),
  (558, 'Economia Pubblica Applicati', 56, 'magistrale'),
  (559, 'Sociologia per la Ricerca', 36, 'triennale'),
  (560, 'Comunicazione Politica per la Ricerca', 72, 'magistrale'),
  (561, 'Comunicazione Politica II', 72, 'triennale'),
  (562, 'Economia Pubblica Base', 72, 'magistrale'),
  (563, 'Diritto Pubblico Avanzati', 36, 'magistrale'),
  (564, 'Geopolitica Base', 56, 'magistrale'),
  (565, 'Politica Comparata Applicati', 56, 'triennale'),
  (566, 'Politica Comparata per le Scienze Sociali', 56, 'magistrale'),
  (567, 'Relazioni Internazionali per le Scienze Sociali', 72, 'triennale'),
  (568, 'Teoria Politica per Professionisti', 56, 'magistrale'),
  (569, 'Teoria Politica I', 72, 'triennale'),
  (570, 'Geopolitica Applicati', 36, 'triennale'),
  (571, 'Politica Comparata per la Ricerca', 36, 'magistrale'),
  (572, 'Teoria Politica e Laboratorio', 36, 'triennale'),
  (573, 'Economia Pubblica per la Ricerca', 18, 'triennale'),
  (574, 'Teoria Politica per le Scienze Sociali', 36, 'magistrale'),
  (575, 'Economia Pubblica I', 56, 'triennale'),
  (576, 'Teoria Politica Base', 36, 'triennale'),
  (577, 'Scienza Politica per le Scienze Sociali', 56, 'magistrale'),
  (578, 'Comunicazione Politica per la Salute', 56, 'magistrale'),
  (579, 'Diritto Pubblico per l''Ingegneria', 18, 'magistrale'),
  (580, 'Geopolitica e Laboratorio', 36, 'magistrale'),
  (581, 'Comunicazione Politica per le Scienze Sociali', 72, 'triennale'),
  (582, 'Teoria Politica e Tecniche', 56, 'magistrale'),
  (583, 'Relazioni Internazionali e Sperimentazione', 36, 'magistrale'),
  (584, 'Teoria Politica Fondamentali', 72, 'triennale'),
  (585, 'Scienza Politica Applicati', 56, 'triennale'),
  (586, 'Politica Comparata per Professionisti', 56, 'magistrale'),
  (587, 'Politiche Pubbliche per Professionisti', 72, 'magistrale'),
  (588, 'Relazioni Internazionali Applicati', 18, 'triennale'),
  (589, 'Scienza Politica e Laboratorio', 36, 'magistrale'),
  (590, 'Scienza Politica Base', 18, 'magistrale'),
  (591, 'Diritto Pubblico per la Ricerca', 72, 'triennale'),
  (592, 'Comunicazione Politica e Sperimentazione', 36, 'triennale'),
  (593, 'Diritto Pubblico Fondamentali', 56, 'magistrale'),
  (594, 'Economia Pubblica per le Scienze Sociali', 56, 'magistrale'),
  (595, 'Comunicazione Politica Applicati', 72, 'magistrale'),
  (596, 'Comunicazione Politica Fondamentali', 56, 'magistrale'),
  (597, 'Economia Pubblica per la Salute', 36, 'triennale'),
  (598, 'Politiche Pubbliche per l''Ingegneria', 56, 'triennale'),
  (599, 'Politica Comparata Avanzati', 18, 'triennale'),
  (600, 'Politiche Pubbliche I', 72, 'triennale');