CREATE TABLE
    DIPARTIMENTO (
        NOME VARCHAR(100) PRIMARY KEY,
        RECAPITO VARCHAR(100) NOT NULL,
        N_AFFERENTI INT NOT NULL DEFAULT 1,
        DIRETTORE VARCHAR(16)
    );

CREATE TABLE
    AFFERENTE (
        CODICE_FISCALE VARCHAR(16) PRIMARY KEY,
        NOME VARCHAR(50) NOT NULL,
        COGNOME VARCHAR(50) NOT NULL,
        DATA_NASCITA DATE NOT NULL,
        LUOGO_NASCITA VARCHAR(100) NOT NULL,
        TEMPO VARCHAR(8) NOT NULL,
        RUOLO VARCHAR(11) NOT NULL,
        TITOLO_STUDIO VARCHAR(20) NOT NULL,
        UNIVERSITA VARCHAR(100) NOT NULL,
        NOME_DIPARTIMENTO VARCHAR(100),
        PUNTEGGIO INT,
        RELATORE VARCHAR(100),
        FASCIA VARCHAR(7),
        STATO VARCHAR(14),

        FOREIGN KEY (NOME_DIPARTIMENTO) REFERENCES DIPARTIMENTO (NOME),

        CHECK (TEMPO IN ('pieno', 'parziale')),
        CHECK (
            (RUOLO = 'professore' AND FASCIA IS NOT NULL AND FASCIA IN ('prima', 'seconda') AND STATO IS NULL)
            OR
            (RUOLO = 'ricercatore' AND STATO IS NOT NULL AND STATO IN ('confermato', 'non confermato') AND FASCIA IS NULL)
        ),
        CHECK (
            ((TITOLO_STUDIO = 'laurea' AND PUNTEGGIO IS NOT NULL AND RELATORE IS NULL) AND (PUNTEGGIO >= 66 AND PUNTEGGIO <= 110))
            OR
            (TITOLO_STUDIO = 'dottorato di ricerca' AND PUNTEGGIO IS NULL AND RELATORE IS NOT NULL)
        ) 
    );

CREATE TABLE
    CORSO (
        ID INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        ORE INT NOT NULL,
        LAUREA VARCHAR(100) NOT NULL
    );

CREATE TABLE
    TIENE (
        CODICE_FISCALE VARCHAR(16),
        ID INT,

        PRIMARY KEY (CODICE_FISCALE, ID),
        FOREIGN KEY (CODICE_FISCALE) REFERENCES AFFERENTE (CODICE_FISCALE),
        FOREIGN KEY (ID) REFERENCES CORSO (ID)
    );

CREATE TABLE
    RICHIEDE (
        ID_CORSO INT,
        ID_CORSO_RICHIESTO INT,

        PRIMARY KEY (ID_CORSO, ID_CORSO_RICHIESTO),
        FOREIGN KEY (ID_CORSO) REFERENCES CORSO (ID),
        FOREIGN KEY (ID_CORSO_RICHIESTO) REFERENCES CORSO (ID),

        CHECK (ID_CORSO_RICHIESTO <> ID_CORSO)
    );

ALTER TABLE DIPARTIMENTO
    ADD CONSTRAINT FK_DIRETTORE
    FOREIGN KEY (DIRETTORE) REFERENCES AFFERENTE(CODICE_FISCALE);