DELIMITER $$

/*IL NUMERO DI AFFERENTI VIENE FISSATO A 1 SU CREAZIONE DEL DIPARTIMENTO (UNICO AFFERENTE IL DIRETTORE)*/
CREATE TRIGGER SET_N_AFFERENTI
    BEFORE INSERT ON DIPARTIMENTO
    FOR EACH ROW
    BEGIN
        NEW.N_AFFERENTI := 1;
        RETURN NEW;
    END;

/*IL NUMERO DI AFFERENTI VIENE INCREMENTATO DI 1 SU CREAZIONE DI UN AFFERENTE SE SPECIFICATO IL DIPARTIMENTO*/
CREATE TRIGGER AGGIORNA_N_AFFERENTI_INSERT
    AFTER INSERT ON AFFERENTE
    FOR EACH ROW
    BEGIN
        IF NEW.NOME_DIPARTIMENTO IS NOT NULL THEN
            UPDATE DIPARTIMENTO SET N_AFFERENTI = N_AFFERENTI + 1 WHERE NOME = NEW.NOME_DIPARTIMENTO;
        END IF;
    END;

/*IL NUMERO DI AFFERENTI VIENE DECREMENTATO DI 1 SU CANCELLAZIONE DI UN AFFERENTE SE SPECIFICATO IL DIPARTIMENTO*/
CREATE TRIGGER AGGIORNA_N_AFFERENTI_DELETE
    AFTER DELETE ON AFFERENTE
    FOR EACH ROW
    BEGIN
        IF OLD.NOME_DIPARTIMENTO IS NOT NULL THEN
            UPDATE DIPARTIMENTO SET N_AFFERENTI = N_AFFERENTI - 1 WHERE NOME = OLD.NOME_DIPARTIMENTO;
        END IF;
    END;

/*IL NUMERO DI AFFERENTI VIENE AGGIORNATO SE NECESSARIO DOPO AVER MODIFICATO UN AFFERENTE*/
CREATE TRIGGER AGGIORNA_N_AFFERENTI_UPDATE
    BEFORE UPDATE ON AFFERENTE
    FOR EACH ROW
    BEGIN
        IF (OLD.NOME_DIPARTIMENTO <> NEW.NOME_DIPARTIMENTO) THEN
            IF OLD.NOME_DIPARTIMENTO IS NOT NULL THEN
                UPDATE DIPARTIMENTO SET N_AFFERENTI = N_AFFERENTI - 1 WHERE NOME = OLD.NOME_DIPARTIMENTO;
            END IF;
            IF NEW.NOME_DIPARTIMENTO IS NOT NULL THEN
                UPDATE DIPARTIMENTO SET N_AFFERENTI = N_AFFERENTI + 1 WHERE NOME = NEW.NOME_DIPARTIMENTO;
            END IF;
        END IF;
    END;

/*PERMETTE LA CANCELLAZIONE DI UN AFFERENTE SOLAMENTE SE NON TIENE CORSI E NON APPARTIENE A NESSUN DIPARTIMENTO*/
CREATE TRIGGER AFFERENTE_DELETE
    BEFORE DELETE ON AFFERENTE
    FOR EACH ROW
    BEGIN
        IF OLD.DIPARTIMENTO IS NOT NULL THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Errore: non è possibile eliminare un afferente che appartiene a un dipartimento';
        ELSE 
            DECLARE CORSI_INSEGNATI INT;
            SELECT COUNT(*) INTO CORSI_INSEGNATI FROM TIENE WHERE CODICE_FISCALE = OLD.CODICE_FISCALE;
            IF CORSI > 0 THEN
                SIGNAL SQLSTATE '45001'
                SET MESSAGE_TEXT = 'Errore: non è possibile eliminare un afferente che insegna corsi';
            END IF;
        END IF;
    END;

/*CONTROLLA CHE IL DIRETTORE SIA EFFETTIVAMENTE UN PROFESSORE DI PRIMA FASCIA*/
CREATE TRIGGER VERIFICA_DIRETTORE
    BEFORE INSERT OR UPDATE ON DIPARTIMENTO
    FOR EACH ROW
    BEGIN
        DECLARE DIRETTORE_VALIDO varchar(16);
        SELECT CODICE_FISCALE INTO DIRETTORE_VALIDO FROM AFFERENTE WHERE (CODICE_FISCALE = NEW.DIRETTORE AND NOME_ DIPARTIMENTO = NEW.NOME AND RUOLO = 'professore' AND FASCIA = 'prima') LIMIT 1;
        IF DIRETTORE_VALIDO IS NULL THEN
            SIGNAL SQLSTATE '45002'
            SET MESSAGE_TEXT = 'Errore: Il Direttore deve essere un Professore di Prima Fascia del Dipartimento';
        END IF;
    END;

DELIMITER ;